"""The PM gate's BEHAVIOUR TESTS, parked by fixture — moved here by prompt 3.1b-2c.

WHY THIS FILE EXISTS
--------------------
Three modules proved the design PM gate was unreachable while it was being built:
tests_design_pm_gate_inert (3.1a), tests_design_pm_rejected_inert (the pm_rejected schema
prompt) and tests_design_pm_approval (3.1b-1). Each held two kinds of test:

  * 15 ABSENCE PROOFS — "nothing writes this status". Prompt 3.1b-2c made both gate
    statuses reachable, so those became false and were dropped. Their obligation passed to
    tests_design_pm_gate_live, which asserts the EXACT set of product writers of each gate
    status (EXECUTION_MODULE_DEFERRED.md §D24).
  * 61 BEHAVIOUR TESTS — the status declarations, the CHECK constraint, the mirror
    derivation, guard parity, the ladder answers, attempt causes, and the PM's queue,
    approve, reject, refusals and workspace read. Those still pin something true, and are
    here, moved verbatim.

THE MOVE CHANGED THREE THINGS AND NOTHING ELSE (each approved before it was made):
  1. three class names that collided once the modules shared a namespace, prefixed by
     origin (PmGate... / PmRejected...) — merged as they were, the second definition of each
     would have silently replaced the first and nine tests would never have been collected;
     one of the two byte-identical _profile() helpers was dropped for the same reason;
  2. RejectTests test_01 and test_02 — the PM's reject now lands at pm_rejected, not
     awaiting_head_qc: three asserts;
  3. three fixture docstrings that cited the dropped allow-lists.

THESE TESTS PARK A ROW BY FIXTURE (PmGateBase._park_in_pm_gate, RejectedBase._park_rejected)
because they test what a status DOES, not how it is reached. Every test that reaches a gate
status through the product is in tests_design_pm_gate_live, which uses no fixture writer.
The section letters in the banners below are the retired modules' own.
"""
from datetime import timedelta
from decimal import Decimal

from django.contrib.auth.models import User
from django.contrib.messages import get_messages
from django.db import IntegrityError, transaction
from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from . import design_views
from .design_analytics import _failure_rows
from .design_metrics import (
    CAUSE_UNCATEGORISED, HEAD_ACTION_STAGES, QC_ACTION_STAGES, STAGE_LABELS, STAGE_ORDER,
    _classify, attempt_cause_split, attention_list, classify_attempt_causes, is_overdue,
)
from .design_views import (
    ARKA_SUBMITTABLE_STATUSES, CHANGE_REQUEST_STATUSES, DESIGN_MIRROR_STATE_MAP,
    REALLOCATABLE_STATUSES, _DESIGNER_ACTIONS, derive_design_mirror_state,
    designer_dashboard_context,
)
from .models import (
    DesignAssignment, DesignAttempt, DueDateCommitment, Program, Project, StatusTransition,
    Task,
    ATTEMPT_REASON_INITIAL, ATTEMPT_REASON_PM_REJECTED, DESIGN_ATTEMPT_REASON_CHOICES,
    DESIGN_ASSIGNMENT_STATUS_CHOICES, DESIGN_ARTIFACTS_UPLOADED, DESIGN_AWAITING_ALLOCATION,
    DESIGN_AWAITING_HEAD_QC, DESIGN_AWAITING_PM_APPROVAL, DESIGN_AWAITING_SURVEY,
    DESIGN_CLOCK_STOPPED_STATUSES, DESIGN_IN_DESIGN, DESIGN_IN_QC,
    DESIGN_NOT_WITH_DESIGNER_STATUSES, DESIGN_PM_REJECTED, DESIGN_RELEASED,
    DESIGN_SURVEY_RETURNED, DESIGN_WORK_FINISHED_STATUSES,
    ERR_LAYOUT, ERR_REQUIREMENT_CHANGED, ERR_SURVEY_INADEQUATE, ERROR_GROUP_A,
    ERROR_GROUP_B, ERROR_GROUP_C, REASON_DESIGN_PM_APPROVED, REASON_DESIGN_PM_REJECTED,
    SUBJECT_DESIGN_ASSIGNMENT,
)
from .views import TENDER_DESIGN_SUBMITTED_STATUSES


# ###########################################################################
# FROM tests_design_pm_gate_inert.py (prompt 3.1a) — sections (b)-(e)
# ###########################################################################

# ===========================================================================
# (b) THE DECLARATION — the audit's §1.4 classification, written by hand
# ===========================================================================
#
# A STATEMENT OF INTENT, NOT A RECORDING. Each entry below is transcribed from
# docs/DESIGN_APPROVAL_AUDIT.md §1.4 and carries that document's reason. None is
# generated by reading the lists: a test that imports the table it checks agrees with any
# mistake the table contains.

class PmGateDeclarationTests(TestCase):

    def test_01_the_choices_place_it_immediately_before_released(self):
        values = [v for v, _ in DESIGN_ASSIGNMENT_STATUS_CHOICES]
        self.assertEqual(values.index(DESIGN_AWAITING_PM_APPROVAL) + 1,
                         values.index(DESIGN_RELEASED))
        self.assertEqual(dict(DESIGN_ASSIGNMENT_STATUS_CHOICES)[DESIGN_AWAITING_PM_APPROVAL],
                         'Awaiting PM approval')
        self.assertLessEqual(len(DESIGN_AWAITING_PM_APPROVAL),
                             DesignAssignment._meta.get_field('status').max_length)

    def test_02_lists_that_MUST_contain_it(self):
        # "The designer's work is done" — the Head has passed it. §1.4: Yes.
        self.assertIn(DESIGN_AWAITING_PM_APPROVAL, DESIGN_WORK_FINISHED_STATUSES)
        self.assertIn(DESIGN_RELEASED, DESIGN_WORK_FINISHED_STATUSES)
        # The artifact has been handed over; leaving it out flips the CEO pill
        # Done -> Not Done between the Head's pass and release. §1.4: Yes.
        self.assertIn(DESIGN_AWAITING_PM_APPROVAL, TENDER_DESIGN_SUBMITTED_STATUSES)
        # One entry per status, and exhaustiveness is test-enforced. §1.4: needs its own entry.
        self.assertIn(DESIGN_AWAITING_PM_APPROVAL, DESIGN_MIRROR_STATE_MAP)
        # One entry per status, or the card renders blank. §1.4: needs its own entry.
        self.assertIn(DESIGN_AWAITING_PM_APPROVAL, _DESIGNER_ACTIONS)
        # One tile per bottleneck, never merged; its own entry before 'released'.
        # §1.4: Yes, as its own entry.
        self.assertIn('awaiting_pm_approval', STAGE_LABELS)

    def test_03_the_stage_sits_immediately_before_released_and_released_stays_last(self):
        keys = [k for k, _ in STAGE_ORDER]
        self.assertEqual(keys.index('awaiting_pm_approval') + 1, keys.index('released'))
        # tender_dashboard.html reads the release tile as `m.stages|last`.
        self.assertEqual(keys[-1], 'released')

    def test_04_lists_that_must_NOT_contain_it(self):
        # Work not yet started — a Head-passed design is far past reallocation. §1.4: No.
        self.assertNotIn(DESIGN_AWAITING_PM_APPROVAL, REALLOCATABLE_STATUSES)
        # The designer may submit an Arka — not once both gates have passed. §1.4: No.
        self.assertNotIn(DESIGN_AWAITING_PM_APPROVAL, ARKA_SUBMITTABLE_STATUSES)
        # The change window. §1.4 left it undecided; prompt 3.1c owns the decision, and
        # until it lands the window is left exactly as it was.
        self.assertNotIn(DESIGN_AWAITING_PM_APPROVAL, CHANGE_REQUEST_STATUSES)
        # Ball in the Design Head's court — it is in the PM's. §1.4: No.
        self.assertNotIn('awaiting_pm_approval', HEAD_ACTION_STAGES)
        # Ball in Design QC's court — it is in the PM's. §1.4: No.
        self.assertNotIn('awaiting_pm_approval', QC_ACTION_STAGES)


# ===========================================================================
# Fixtures for (c)–(e)
# ===========================================================================

def _profile(username, role, is_design_head=False):
    """A post_save signal auto-creates the UserProfile; fetch and set, never create."""
    user = User.objects.create_user(username=username, password='x')
    profile = user.profile
    profile.role = role
    profile.is_active = True
    profile.is_design_head = is_design_head
    profile.save()
    return profile


class PmGateBase(TestCase):

    def setUp(self):
        self.head     = _profile('pg_head', 'Design', is_design_head=True)
        self.designer = _profile('pg_des',  'Design')
        self.program = Program.objects.create(
            name='Test-PMGate', program_type='OPEX', client_name='PGClient',
            status='Active', short_tender_code='PG')
        self.today = timezone.localdate()

    def _site(self, code, status=DESIGN_IN_QC):
        """An allocated site with an APPROVED agreed date, at `status`."""
        site = Project(
            project_id=code, customer_name='PGClient', customer_phone='9876543210',
            site_address='1 Sun Rd', city='Delhi', project_type='OPEX',
            program=self.program, site_code=code,
            dc_capacity_kw=Decimal('100.00'), status='Draft')
        site.save()
        assignment = DesignAssignment.objects.create(
            project=site, status=status, assigned_to=self.designer,
            assigned_by=self.head, assigned_at=timezone.now(),
            survey_file_bucket='b', survey_file_path=f'{code}/survey/x.pdf')
        DueDateCommitment.objects.create(
            assignment=assignment, proposed_date=self.today + timedelta(days=5),
            proposed_by=self.head, approved_by=self.head, approved_at=timezone.now(),
            is_current=True)
        return site, assignment

    def _park_in_pm_gate(self, assignment):
        """FIXTURE WRITER — parks a row at awaiting_pm_approval with a queryset update(),
        for tests of what the status DOES rather than how it is reached. The product
        writers are pinned by tests_design_pm_gate_live."""
        DesignAssignment.objects.filter(pk=assignment.pk).update(status=DESIGN_AWAITING_PM_APPROVAL)
        assignment.refresh_from_db()
        return assignment

    def _login(self, profile):
        self.assertTrue(self.client.login(username=profile.user.username, password='x'))

    def _messages(self, response):
        return ' '.join(str(m) for m in get_messages(response.wsgi_request))


# ===========================================================================
# (c) The mirror derivation
# ===========================================================================

class PmGateMirrorDerivationTests(TestCase):

    def test_01_derive_does_not_raise_and_matches_awaiting_head_qc(self):
        state = derive_design_mirror_state(DESIGN_AWAITING_PM_APPROVAL)
        self.assertEqual(state, Task.IN_PROGRESS)
        # A design with the PM is not released: the same mirror state as the last gate.
        self.assertEqual(state, derive_design_mirror_state(DESIGN_AWAITING_HEAD_QC))


# ===========================================================================
# (d) The five "work finished" guards — each refuses a site in the new status
# ===========================================================================

class WorkFinishedGuardTests(PmGateBase):
    """Each guard is asserted on its own, against a control site at `in_design` that the
    same guard ALLOWS — so the refusal is shown to come from the status and nothing else.
    (The control was `in_qc` until the D13 prompt closed the Design Hold there.)"""

    # ── 1. design_my_sites → can_request_extension ───────────────────────────────
    def test_01_can_request_extension_is_false_in_the_pm_gate(self):
        _, control = self._site('PG-EXT-C', status=DESIGN_IN_DESIGN)
        _, parked = self._site('PG-EXT-P')
        self._park_in_pm_gate(parked)
        self._login(self.designer)
        rows = {r['assignment'].pk: r for r in
                self.client.get(reverse('design_my_sites')).context['rows']}
        self.assertTrue(rows[control.pk]['can_request_extension'])
        self.assertFalse(rows[parked.pk]['can_request_extension'])
        # The Design Hold control's flag, and `is_released` left truthful beside it.
        self.assertTrue(rows[parked.pk]['not_with_designer'])
        self.assertFalse(rows[parked.pk]['is_released'])
        self.assertFalse(rows[control.pk]['not_with_designer'])

    # ── 2. design_due_date_propose ───────────────────────────────────────────────
    def test_02_extension_request_is_refused_in_the_pm_gate(self):
        control_site, control = self._site('PG-PRO-C', status=DESIGN_IN_DESIGN)
        parked_site, parked = self._site('PG-PRO-P')
        self._park_in_pm_gate(parked)
        self._login(self.designer)
        data = {'proposed_date': str(self.today + timedelta(days=20)),
                'change_reason': 'more time'}

        self.client.post(reverse('design_due_date_propose',
                                 kwargs={'project_id': control_site.project_id}), data)
        self.assertEqual(control.due_date_commitments.count(), 2)

        response = self.client.post(reverse('design_due_date_propose',
                                            kwargs={'project_id': parked_site.project_id}), data)
        self.assertEqual(parked.due_date_commitments.count(), 1)
        self.assertIn('with the PM for approval', self._messages(response))

    # ── 3. design_due_date_change ────────────────────────────────────────────────
    def test_03_head_date_change_is_refused_in_the_pm_gate(self):
        control_site, control = self._site('PG-CHG-C', status=DESIGN_IN_DESIGN)
        parked_site, parked = self._site('PG-CHG-P')
        self._park_in_pm_gate(parked)
        self._login(self.head)
        data = {'proposed_date': str(self.today + timedelta(days=9)),
                'change_reason': 'pulled in'}

        self.client.post(reverse('design_due_date_change',
                                 kwargs={'project_id': control_site.project_id}), data)
        self.assertEqual(control.due_date_commitments.count(), 2)

        response = self.client.post(reverse('design_due_date_change',
                                            kwargs={'project_id': parked_site.project_id}), data)
        self.assertEqual(parked.due_date_commitments.count(), 1)
        self.assertIn('with the PM for approval', self._messages(response))

    # ── 4. design_mark_blocked ───────────────────────────────────────────────────
    def test_04_design_hold_is_refused_in_the_pm_gate(self):
        """The §6.1 second door: a hold here would clear back to `in_design`."""
        control_site, control = self._site('PG-BLK-C', status=DESIGN_IN_DESIGN)
        parked_site, parked = self._site('PG-BLK-P')
        self._park_in_pm_gate(parked)
        self._login(self.designer)

        self.client.post(reverse('design_mark_blocked',
                                 kwargs={'project_id': control_site.project_id}),
                         {'reason': 'survey is wrong'})
        control.refresh_from_db()
        self.assertEqual(control.status, DESIGN_SURVEY_RETURNED)

        response = self.client.post(reverse('design_mark_blocked',
                                            kwargs={'project_id': parked_site.project_id}),
                                    {'reason': 'survey is wrong'})
        parked.refresh_from_db()
        self.assertEqual(parked.status, DESIGN_AWAITING_PM_APPROVAL)
        self.assertIsNone(parked.survey_returned_at)
        self.assertIn('with the PM for approval', self._messages(response))

    # ── 5. designer_dashboard_context → can_mark_blocked ─────────────────────────
    def test_05_can_mark_blocked_is_false_in_the_pm_gate(self):
        control_site, _ = self._site('PG-CMB-C', status=DESIGN_IN_DESIGN)
        parked_site, parked = self._site('PG-CMB-P')
        self._park_in_pm_gate(parked)
        ctx = designer_dashboard_context(
            self.designer, [Project.objects.get(pk=control_site.pk),
                            Project.objects.get(pk=parked_site.pk)])
        self.assertTrue(ctx[control_site.pk]['can_mark_blocked'])
        self.assertFalse(ctx[parked_site.pk]['can_mark_blocked'])

    # ── and the Head's screen flag that mirrors guard 3 ──────────────────────────
    def test_06_head_sites_flag_hides_change_date_in_the_pm_gate(self):
        control_site, _ = self._site('PG-HS-C', status=DESIGN_IN_DESIGN)
        parked_site, parked = self._site('PG-HS-P')
        self._park_in_pm_gate(parked)
        self._login(self.head)
        rows = {r['site'].pk: r for r in self.client.get(
            reverse('design_head_sites', kwargs={'pk': self.program.pk})).context['rows']}
        self.assertFalse(rows[control_site.pk]['clock_stopped'])
        self.assertTrue(rows[parked_site.pk]['clock_stopped'])


# ===========================================================================
# (e) _classify() and _DESIGNER_ACTIONS answer explicitly — plus the clock (B6)
# ===========================================================================

class PmGateLadderAnswerTests(PmGateBase):

    def test_01_classify_returns_its_own_stage_never_in_design(self):
        _, parked = self._site('PG-CL')
        self._park_in_pm_gate(parked)
        stage = _classify(parked, None)
        self.assertEqual(stage, 'awaiting_pm_approval')
        self.assertNotEqual(stage, 'in_design')
        self.assertEqual(STAGE_LABELS[stage], 'Awaiting PM approval')

    def test_02_designer_actions_offer_nothing_and_say_who_holds_it(self):
        kind, label, waiting = _DESIGNER_ACTIONS[DESIGN_AWAITING_PM_APPROVAL]
        self.assertEqual((kind, label), ('none', ''))
        self.assertTrue(waiting.strip())
        self.assertIn('PM', waiting)

    def test_03_is_overdue_stops_the_designers_clock(self):
        _, parked = self._site('PG-OD')
        self._park_in_pm_gate(parked)
        past = parked.due_date_commitments.get()
        past.proposed_date = self.today - timedelta(days=10)
        past.save(update_fields=['proposed_date'])
        self.assertFalse(is_overdue(parked, past, self.today))
        # Control: the same row back at in_qc IS overdue.
        parked.status = DESIGN_IN_QC
        self.assertTrue(is_overdue(parked, past, self.today))

    def test_04_attention_list_does_not_list_revisions_for_a_parked_site(self):
        _, parked = self._site('PG-AT')
        self._park_in_pm_gate(parked)
        site = {'assignment': parked, 'project': parked.project, 'designer': self.designer,
                'stage': _classify(parked, None), 'overdue': False, 'days_over': 0,
                'pending_crs': [], 'blocked': False, 'revisions': 5, 'released': False,
                'arka': None}
        self.assertEqual(attention_list([site], self.today), [])
        # Control: the same site at in_qc is listed for its revisions.
        parked.status = DESIGN_IN_QC
        site['stage'] = _classify(parked, None)
        self.assertEqual(len(attention_list([site], self.today)), 1)

# ###########################################################################
# FROM tests_design_pm_rejected_inert.py (the pm_rejected schema prompt) — sections (b)-(f)
# ###########################################################################

# ===========================================================================
# (b) THE DECLARATION — written by hand, never generated from the lists
# ===========================================================================
#
# A STATEMENT OF INTENT, NOT A RECORDING. Each line carries the pre-flight's (A3) reason. A
# test that imported the table it checks would agree with any mistake the table contains.

class PmRejectedDeclarationTests(TestCase):

    def test_01_the_choices(self):
        values = [v for v, _ in DESIGN_ASSIGNMENT_STATUS_CHOICES]
        self.assertEqual(dict(DESIGN_ASSIGNMENT_STATUS_CHOICES)[DESIGN_PM_REJECTED],
                         'PM rejected — awaiting Design Head')
        # Immediately BEFORE awaiting_pm_approval, so that awaiting_pm_approval stays
        # immediately before released — 3.1a's ordering test.
        self.assertEqual(values.index(DESIGN_PM_REJECTED) + 1,
                         values.index(DESIGN_AWAITING_PM_APPROVAL))
        self.assertEqual(values.index(DESIGN_AWAITING_PM_APPROVAL) + 1,
                         values.index(DESIGN_RELEASED))
        self.assertEqual(dict(DESIGN_ATTEMPT_REASON_CHOICES)[ATTEMPT_REASON_PM_REJECTED],
                         'PM rejected')
        self.assertLessEqual(len(DESIGN_PM_REJECTED),
                             DesignAssignment._meta.get_field('status').max_length)
        self.assertLessEqual(len(ATTEMPT_REASON_PM_REJECTED),
                             DesignAttempt._meta.get_field('opened_reason').max_length)

    def test_02_lists_that_MUST_contain_it(self):
        # Submitted and bounced — the `qc_failed` note on the list; leaving it out flips
        # the CEO's design pill backwards on a rejection.
        self.assertIn(DESIGN_PM_REJECTED, TENDER_DESIGN_SUBMITTED_STATUSES)
        # One entry per status or derive raises. In Progress: not released.
        self.assertEqual(DESIGN_MIRROR_STATE_MAP[DESIGN_PM_REJECTED], Task.IN_PROGRESS)
        # One entry per status, or the card renders blank.
        self.assertIn(DESIGN_PM_REJECTED, _DESIGNER_ACTIONS)
        # The guards' question: the designer does not hold a PM-rejected package.
        self.assertIn(DESIGN_PM_REJECTED, DESIGN_NOT_WITH_DESIGNER_STATUSES)

    def test_03_lists_that_must_NOT_contain_it(self):
        # Product decision D2: a PM-rejected package is not finished — out of every
        # attempt-figure denominator while it is with the Head.
        self.assertNotIn(DESIGN_PM_REJECTED, DESIGN_WORK_FINISHED_STATUSES)
        # Product decision D3: not a change-request window.
        self.assertNotIn(DESIGN_PM_REJECTED, CHANGE_REQUEST_STATUSES)
        # An Arka exists; reallocating would orphan its artifacts.
        self.assertNotIn(DESIGN_PM_REJECTED, REALLOCATABLE_STATUSES)
        # The designer does not hold it, so may not submit an Arka onto it.
        self.assertNotIn(DESIGN_PM_REJECTED, ARKA_SUBMITTABLE_STATUSES)

    def test_04_no_stage_of_its_own_and_the_stage_list_is_unchanged(self):
        """Folded into 'awaiting_head_qc' (decision 1): review_queue_age() takes ONE package
        stage, and a new tile would change every tender dashboard."""
        self.assertEqual([k for k, _ in STAGE_ORDER], [
            'awaiting_survey', 'awaiting_allocation', 'allocated', 'due_date_proposed',
            'in_design', 'arka_submitted', 'awaiting_head_arka', 'arka_approved',
            'artifacts_uploaded', 'in_qc', 'awaiting_head_qc', 'blocked',
            'awaiting_pm_approval', 'released'])
        # HEAD_ACTION_STAGES follows from the fold; QC_ACTION_STAGES is not the Head's.
        self.assertIn('awaiting_head_qc', HEAD_ACTION_STAGES)
        self.assertNotIn('awaiting_head_qc', QC_ACTION_STAGES)

    def test_05_the_guard_set_is_the_finished_set_plus_one_and_D13_joins_the_hold_set(self):
        # The D13 prompt split the guard set in two (R-5). The DATE guards' set keeps the
        # membership this test pinned before: the finished set plus one.
        self.assertEqual(DESIGN_CLOCK_STOPPED_STATUSES,
                         DESIGN_WORK_FINISHED_STATUSES | {DESIGN_PM_REJECTED})
        # §D13: the designer does not hold these either, and a hold there was the live
        # reopen route. The D13 prompt (13 Sep 2026) added them to the HOLD guards' set —
        # this is the assertion it deliberately changed. They stay out of the clock set:
        # is_overdue() still counts them, so their due date stays open to change.
        review = {DESIGN_ARTIFACTS_UPLOADED, DESIGN_IN_QC, DESIGN_AWAITING_HEAD_QC}
        self.assertEqual(DESIGN_NOT_WITH_DESIGNER_STATUSES,
                         DESIGN_CLOCK_STOPPED_STATUSES | review)
        for status in review:
            self.assertNotIn(status, DESIGN_CLOCK_STOPPED_STATUSES)


# ===========================================================================
# Fixtures for (c)–(f)
# ===========================================================================

class RejectedBase(TestCase):

    def setUp(self):
        self.head     = _profile('pr_head', 'Design', is_design_head=True)
        self.designer = _profile('pr_des',  'Design')
        self.program = Program.objects.create(
            name='Test-PMRejected', program_type='OPEX', client_name='PRClient',
            status='Active', short_tender_code='PR')
        self.today = timezone.localdate()

    def _site(self, code, status=DESIGN_IN_QC):
        """An allocated site with an APPROVED agreed date, at `status`."""
        site = Project(
            project_id=code, customer_name='PRClient', customer_phone='9876543210',
            site_address='1 Sun Rd', city='Delhi', project_type='OPEX',
            program=self.program, site_code=code,
            dc_capacity_kw=Decimal('100.00'), status='Draft')
        site.save()
        assignment = DesignAssignment.objects.create(
            project=site, status=status, assigned_to=self.designer,
            assigned_by=self.head, assigned_at=timezone.now(),
            survey_file_bucket='b', survey_file_path=f'{code}/survey/x.pdf')
        DueDateCommitment.objects.create(
            assignment=assignment, proposed_date=self.today + timedelta(days=5),
            proposed_by=self.head, approved_by=self.head, approved_at=timezone.now(),
            is_current=True)
        return site, assignment

    def _park_rejected(self, assignment):
        """FIXTURE WRITER — parks a row at pm_rejected with a queryset update(), for tests
        of what the status DOES. The product writers are pinned by
        tests_design_pm_gate_live."""
        DesignAssignment.objects.filter(pk=assignment.pk).update(status=DESIGN_PM_REJECTED)
        assignment.refresh_from_db()
        return assignment

    @staticmethod
    def _attempt(assignment, number, reason=ATTEMPT_REASON_INITIAL, category='', remarks='',
                 save=True):
        """FIXTURE WRITER — a DesignAttempt carrying the Head's classification fields and an
        opened_reason, saved or not. The product writer of both is design_head_send_back()."""
        attempt = DesignAttempt(
            assignment=assignment, attempt_number=number, opened_reason=reason,
            pm_rejection_category=category, pm_rejection_remarks=remarks)
        if save:
            attempt.save()
        return attempt

    def _login(self, profile):
        self.assertTrue(self.client.login(username=profile.user.username, password='x'))

    def _messages(self, response):
        return ' '.join(str(m) for m in get_messages(response.wsgi_request))


# ===========================================================================
# (c) The CHECK constraint — both directions, enforced by the database
# ===========================================================================

class ConstraintTests(RejectedBase):
    """pm_rejection_remarks_required_with_category: a category requires remarks."""

    def setUp(self):
        super().setUp()
        _, self.assignment = self._site('PR-CK')

    def test_01_both_blank_saves(self):
        """The shape of every existing row. The first draft's constraint refused it, which
        would have failed the migration on all ten attempts in the database."""
        attempt = self._attempt(self.assignment, 1)
        self.assertEqual((attempt.pm_rejection_category, attempt.pm_rejection_remarks), ('', ''))

    def test_02_category_with_blank_remarks_is_refused(self):
        with self.assertRaises(IntegrityError), transaction.atomic():
            self._attempt(self.assignment, 1, category=ERR_LAYOUT)
        self.assertFalse(DesignAttempt.objects.filter(assignment=self.assignment).exists())

    def test_03_category_with_remarks_saves(self):
        attempt = self._attempt(self.assignment, 1, category=ERR_LAYOUT, remarks='wrong rows')
        self.assertEqual(attempt.pm_rejection_category, ERR_LAYOUT)

    def test_04_remarks_without_a_category_saves(self):
        """An implication, not an equivalence: words with no category are not refused by
        the database. Requiring the category is 3.1b-2b's view's job (see B4)."""
        self._attempt(self.assignment, 1, remarks='a note')


# ===========================================================================
# (d) The mirror derivation
# ===========================================================================

class PmRejectedMirrorDerivationTests(TestCase):

    def test_01_derive_does_not_raise_and_matches_the_head_gate(self):
        self.assertEqual(derive_design_mirror_state(DESIGN_PM_REJECTED), Task.IN_PROGRESS)
        self.assertEqual(derive_design_mirror_state(DESIGN_PM_REJECTED),
                         derive_design_mirror_state(DESIGN_AWAITING_HEAD_QC))


# ===========================================================================
# (e) The four guards and three screen flags
# ===========================================================================

class GuardTests(RejectedBase):
    """Each guard on its own, against a control site at `in_design` that the same guard
    ALLOWS, so the refusal is shown to come from the status and nothing else. (The control
    was `in_qc` until the D13 prompt closed the Design Hold there.)"""

    # ── 1. design_due_date_propose ───────────────────────────────────────────────
    def test_01_extension_request_is_refused(self):
        control_site, control = self._site('PR-PRO-C', status=DESIGN_IN_DESIGN)
        parked_site, parked = self._site('PR-PRO-P')
        self._park_rejected(parked)
        self._login(self.designer)
        data = {'proposed_date': str(self.today + timedelta(days=20)),
                'change_reason': 'more time'}
        self.client.post(reverse('design_due_date_propose',
                                 kwargs={'project_id': control_site.project_id}), data)
        self.assertEqual(control.due_date_commitments.count(), 2)
        response = self.client.post(reverse('design_due_date_propose',
                                            kwargs={'project_id': parked_site.project_id}), data)
        self.assertEqual(parked.due_date_commitments.count(), 1)
        self.assertIn('back with the Design Head after the PM rejected it',
                      self._messages(response))

    # ── 2. design_due_date_change ────────────────────────────────────────────────
    def test_02_head_date_change_is_refused(self):
        control_site, control = self._site('PR-CHG-C', status=DESIGN_IN_DESIGN)
        parked_site, parked = self._site('PR-CHG-P')
        self._park_rejected(parked)
        self._login(self.head)
        data = {'proposed_date': str(self.today + timedelta(days=9)),
                'change_reason': 'pulled in'}
        self.client.post(reverse('design_due_date_change',
                                 kwargs={'project_id': control_site.project_id}), data)
        self.assertEqual(control.due_date_commitments.count(), 2)
        response = self.client.post(reverse('design_due_date_change',
                                            kwargs={'project_id': parked_site.project_id}), data)
        self.assertEqual(parked.due_date_commitments.count(), 1)
        self.assertIn('back with the Design Head after the PM rejected it',
                      self._messages(response))

    # ── 3. design_mark_blocked ───────────────────────────────────────────────────
    def test_03_design_hold_is_refused(self):
        """The reopen door: a hold here would clear back to `in_design`."""
        control_site, control = self._site('PR-BLK-C', status=DESIGN_IN_DESIGN)
        parked_site, parked = self._site('PR-BLK-P')
        self._park_rejected(parked)
        self._login(self.designer)
        self.client.post(reverse('design_mark_blocked',
                                 kwargs={'project_id': control_site.project_id}),
                         {'reason': 'survey is wrong'})
        control.refresh_from_db()
        self.assertEqual(control.status, DESIGN_SURVEY_RETURNED)
        response = self.client.post(reverse('design_mark_blocked',
                                            kwargs={'project_id': parked_site.project_id}),
                                    {'reason': 'survey is wrong'})
        parked.refresh_from_db()
        self.assertEqual(parked.status, DESIGN_PM_REJECTED)
        self.assertIsNone(parked.survey_returned_at)
        self.assertIn('was rejected by the PM and is back with the Design Head',
                      self._messages(response))

    # ── 4. designer_dashboard_context → can_mark_blocked ─────────────────────────
    def test_04_can_mark_blocked_is_false(self):
        control_site, _ = self._site('PR-CMB-C', status=DESIGN_IN_DESIGN)
        parked_site, parked = self._site('PR-CMB-P')
        self._park_rejected(parked)
        ctx = designer_dashboard_context(
            self.designer, [Project.objects.get(pk=control_site.pk),
                            Project.objects.get(pk=parked_site.pk)])
        self.assertTrue(ctx[control_site.pk]['can_mark_blocked'])
        self.assertFalse(ctx[parked_site.pk]['can_mark_blocked'])

    # ── the three screen flags that show those controls ──────────────────────────
    def test_05_my_sites_flags_hide_extension_and_hold(self):
        _, control = self._site('PR-MS-C', status=DESIGN_IN_DESIGN)
        _, parked = self._site('PR-MS-P')
        self._park_rejected(parked)
        self._login(self.designer)
        rows = {r['assignment'].pk: r for r in
                self.client.get(reverse('design_my_sites')).context['rows']}
        self.assertTrue(rows[control.pk]['can_request_extension'])
        self.assertFalse(rows[parked.pk]['can_request_extension'])
        self.assertFalse(rows[control.pk]['not_with_designer'])
        self.assertTrue(rows[parked.pk]['not_with_designer'])

    def test_06_head_sites_flag_hides_change_date(self):
        control_site, _ = self._site('PR-HS-C', status=DESIGN_IN_DESIGN)
        parked_site, parked = self._site('PR-HS-P')
        self._park_rejected(parked)
        self._login(self.head)
        rows = {r['site'].pk: r for r in self.client.get(
            reverse('design_head_sites', kwargs={'pk': self.program.pk})).context['rows']}
        self.assertFalse(rows[control_site.pk]['clock_stopped'])
        self.assertTrue(rows[parked_site.pk]['clock_stopped'])

    # ── and every OTHER status answers exactly as it did before ──────────────────
    def test_07_every_other_status_answers_identically(self):
        """THE STOP CONDITION, as a test. The guards and flags moved from the finished set
        to the new one; for every status except the new one, membership is identical, and
        each flag is re-derived through the real code and compared with the pre-change
        formula (which read DESIGN_WORK_FINISHED_STATUSES).

        The D13 prompt split the guard set. The date guards' set still agrees with the
        finished set for every other status. The hold guards' set also refuses the three
        review statuses — the deliberate D13 difference, named `under_review` below and
        nowhere else."""
        others = [v for v, _ in DESIGN_ASSIGNMENT_STATUS_CHOICES if v != DESIGN_PM_REJECTED]
        under_review = (DESIGN_ARTIFACTS_UPLOADED, DESIGN_IN_QC, DESIGN_AWAITING_HEAD_QC)
        for status in others:
            self.assertEqual(status in DESIGN_CLOCK_STOPPED_STATUSES,
                             status in DESIGN_WORK_FINISHED_STATUSES, status)
            self.assertEqual(status in DESIGN_NOT_WITH_DESIGNER_STATUSES,
                             status in DESIGN_WORK_FINISHED_STATUSES or status in under_review,
                             status)

        sites = {status: self._site(f'PR-ALL-{i:02d}', status=status)
                 for i, status in enumerate(others)}
        ctx = designer_dashboard_context(
            self.designer, [Project.objects.get(pk=s.pk) for s, _ in sites.values()])
        self._login(self.designer)
        my_rows = {r['assignment'].pk: r for r in
                   self.client.get(reverse('design_my_sites')).context['rows']}
        self._login(self.head)
        head_rows = {r['site'].pk: r for r in self.client.get(
            reverse('design_head_sites', kwargs={'pk': self.program.pk})).context['rows']}

        for status, (site, assignment) in sites.items():
            finished = status in DESIGN_WORK_FINISHED_STATUSES
            reviewing = status in under_review
            self.assertEqual(ctx[site.pk]['can_mark_blocked'],
                             status not in (DESIGN_SURVEY_RETURNED, DESIGN_AWAITING_SURVEY,
                                            DESIGN_AWAITING_ALLOCATION)
                             and not finished and not reviewing,
                             status)
            self.assertEqual(my_rows[assignment.pk]['can_request_extension'], not finished,
                             status)
            self.assertEqual(my_rows[assignment.pk]['not_with_designer'],
                             finished or reviewing, status)
            self.assertEqual(head_rows[site.pk]['clock_stopped'], finished, status)


# ===========================================================================
# (e, continued) The ladder answers — _classify, the designer card, the clock
# ===========================================================================

class PmRejectedLadderAnswerTests(RejectedBase):

    def test_01_classify_files_it_with_the_head_explicitly_never_in_design(self):
        _, parked = self._site('PR-CL')
        self._park_rejected(parked)
        self.assertEqual(_classify(parked, None), 'awaiting_head_qc')

    def test_02_designer_card_offers_nothing_and_says_who_holds_it(self):
        kind, label, waiting = _DESIGNER_ACTIONS[DESIGN_PM_REJECTED]
        self.assertEqual((kind, label), ('none', ''))
        self.assertIn('PM', waiting)
        self.assertIn('Design Head', waiting)

    def test_03_is_overdue_is_false_because_the_designer_delivered(self):
        _, parked = self._site('PR-OD')
        self._park_rejected(parked)
        past = parked.due_date_commitments.get()
        past.proposed_date = self.today - timedelta(days=10)
        past.save(update_fields=['proposed_date'])
        self.assertFalse(is_overdue(parked, past, self.today))
        # Control: the same row at in_qc or awaiting_head_qc IS overdue — the designer does
        # not hold those either, which is why "does not hold it" is not the rule.
        for status in (DESIGN_IN_QC, DESIGN_AWAITING_HEAD_QC):
            parked.status = status
            self.assertTrue(is_overdue(parked, past, self.today), status)

    def test_04_attention_lists_it_as_the_heads_not_for_its_revisions(self):
        _, parked = self._site('PR-AT')
        self._park_rejected(parked)
        site = {'assignment': parked, 'project': parked.project, 'designer': self.designer,
                'stage': _classify(parked, None), 'overdue': False, 'days_over': 0,
                'pending_crs': [], 'blocked': False, 'revisions': 5, 'released': False,
                'arka': None}
        rows = attention_list([site], self.today)
        self.assertEqual(len(rows), 1)
        self.assertTrue(rows[0]['reason'].startswith('Waiting on you'), rows[0]['reason'])
        # Control: the same site at in_qc is listed for its revisions.
        parked.status = DESIGN_IN_QC
        site['stage'] = _classify(parked, None)
        self.assertTrue(attention_list([site], self.today)[0]['reason']
                        .startswith('Due date revised'))


# ===========================================================================
# (f) classify_attempt_causes and _failure_rows
# ===========================================================================

class CauseTests(RejectedBase):
    """Unsaved attempts: classify_attempt_causes() and _failure_rows() read rows in hand
    and issue no query, so none is needed."""

    def setUp(self):
        super().setUp()
        _, self.assignment = self._site('PR-CA')

    def _loop(self, category):
        first = self._attempt(self.assignment, 1, category=category,
                              remarks='sent back' if category else '', save=False)
        second = self._attempt(self.assignment, 2, reason=ATTEMPT_REASON_PM_REJECTED,
                               save=False)
        return [first, second]

    def test_01_group_a_charges_the_designer(self):
        attempts = self._loop(ERR_LAYOUT)
        self.assertEqual(classify_attempt_causes(attempts)[2], ERROR_GROUP_A)
        split = attempt_cause_split(attempts)
        self.assertEqual((split['designer'], split['input']), (1, 0))

    def test_02_group_b_and_c_do_not(self):
        for category, group in ((ERR_SURVEY_INADEQUATE, ERROR_GROUP_B),
                                (ERR_REQUIREMENT_CHANGED, ERROR_GROUP_C)):
            attempts = self._loop(category)
            self.assertEqual(classify_attempt_causes(attempts)[2], group)
            split = attempt_cause_split(attempts)
            self.assertEqual((split['designer'], split['input']), (0, 1), category)

    def test_03_blank_is_uncategorised_and_therefore_charged(self):
        """Why 3.1b-2b must require the category on the send-back path."""
        attempts = self._loop('')
        self.assertEqual(classify_attempt_causes(attempts)[2], CAUSE_UNCATEGORISED)
        self.assertEqual(attempt_cause_split(attempts)['designer'], 1)

    def test_04_it_is_never_counted_as_an_initial_attempt(self):
        """The bug the branch closes: the old `else` filed an unknown reason as initial."""
        split = attempt_cause_split(self._loop(ERR_LAYOUT))
        self.assertEqual(split['initial'], 1)

    def test_05_failure_rows_gains_a_PM_source_and_the_other_two_are_unchanged(self):
        first, second = self._loop(ERR_LAYOUT)
        data = {'attempts': [first, second], 'arkas': [], 'attempt_by_id': {},
                'assignment_by_id': {self.assignment.pk: self.assignment}}
        rows = _failure_rows(data)
        self.assertEqual([(r['category'], r['gate'], r['source']) for r in rows],
                         [(ERR_LAYOUT, 'PM', 'Package')])
        # An attempt with only a gate field set reports exactly as before: one row, from
        # that gate, and no PM row (its new field is blank, as on every real row today).
        gate_only = self._attempt(self.assignment, 3, save=False)
        gate_only.head_failure_category = ERR_LAYOUT
        data['attempts'] = [gate_only]
        self.assertEqual([(r['category'], r['gate']) for r in _failure_rows(data)],
                         [(ERR_LAYOUT, 'Design Head')])



# ###########################################################################
# FROM tests_design_pm_approval.py (prompt 3.1b-1) — sections (b)-(g) and B3
# ###########################################################################

EMPTY_STATE = 'No designs are waiting for your approval.'


class PmApprovalBase(PmGateBase):

    def setUp(self):
        super().setUp()
        self.pm       = _profile('pa_pm',    'PM')
        self.other_pm = _profile('pa_pm2',   'PM')
        self.coord    = _profile('pa_coord', 'Project Coordinator')
        self.scm      = _profile('pa_scm',   'SCM')
        self.finance  = _profile('pa_fin',   'Finance')

    def _pm_site(self, code, status=DESIGN_IN_QC, pm=None):
        site, assignment = self._site(code, status)
        Project.objects.filter(pk=site.pk).update(assigned_pm=pm or self.pm)
        site.refresh_from_db()
        return site, assignment

    def _parked(self, code, pm=None):
        site, assignment = self._pm_site(code, pm=pm)
        return site, self._park_in_pm_gate(assignment)

    def _transitions(self, assignment):
        return StatusTransition.objects.filter(
            subject_type=SUBJECT_DESIGN_ASSIGNMENT, subject_id=assignment.pk)

    def _url(self, name, site):
        return reverse(name, kwargs={'project_id': site.project_id})

    def _queue(self, profile):
        self._login(profile)
        response = self.client.get(reverse('design_pm_approval_queue'))
        self.assertEqual(response.status_code, 200)
        return response

    def _queue_ids(self, profile):
        return [row['site'].project_id for row in self._queue(profile).context['rows']]

    def _assert_untouched(self, assignment, status):
        assignment.refresh_from_db()
        self.assertEqual(assignment.status, status)
        self.assertIsNone(assignment.pm_approved_at)
        self.assertIsNone(assignment.pm_approved_by_id)
        self.assertFalse(self._transitions(assignment).exists())


# ===========================================================================
# (b) THE EMPTY QUEUE
# ===========================================================================

class EmptyQueueTests(PmApprovalBase):

    def test_01_renders_200_and_says_so_in_words(self):
        self._pm_site('PA-E1')                       # theirs, but not parked
        response = self._queue(self.pm)
        self.assertEqual(response.context['rows'], [])
        self.assertContains(response, EMPTY_STATE)

    def test_02_the_nav_entry_is_shown_to_pm_and_coordinator_only(self):
        link = reverse('design_pm_approval_queue')
        for profile in (self.pm, self.coord):
            self.assertContains(self._queue(profile), f'href="{link}"')
        for profile in (self.designer, self.head, self.scm, self.finance):
            self.assertNotContains(self._queue(profile), f'href="{link}"')


# ===========================================================================
# (c) THE POPULATED QUEUE
# ===========================================================================

class PopulatedQueueTests(PmApprovalBase):

    def setUp(self):
        super().setUp()
        self.site, self.assignment = self._parked('PA-Q1')
        self.site.coordinators.add(self.coord)
        self._pm_site('PA-Q1-NOT-PARKED')                     # same PM, still in QC
        self._parked('PA-Q2', pm=self.other_pm)               # another PM's parked site

    def test_01_its_own_pm_sees_it(self):
        response = self._queue(self.pm)
        self.assertEqual([r['site'].project_id for r in response.context['rows']], ['PA-Q1'])
        self.assertNotContains(response, EMPTY_STATE)
        self.assertContains(response, self._url('design_pm_approve', self.site))
        self.assertContains(response, self._url('design_pm_reject', self.site))
        self.assertContains(response, self._url('design_site_workspace', self.site))

    def test_02_a_coordinator_on_the_site_sees_it(self):
        self.assertEqual(self._queue_ids(self.coord), ['PA-Q1'])

    def test_03_nobody_else_sees_it(self):
        self.assertEqual(self._queue_ids(self.other_pm), ['PA-Q2'])
        for profile in (self.designer, self.head, self.scm, self.finance):
            self.assertNotIn('PA-Q1', self._queue_ids(profile))

    def test_04_one_row_per_site_however_many_coordinators(self):
        """Pins the queue's .distinct(): the coordinators M2M join would otherwise return
        this site once per coordinator."""
        self.site.coordinators.add(_profile('pa_coord2', 'Project Coordinator'))
        self.assertEqual(self._queue_ids(self.pm), ['PA-Q1'])
        self.assertEqual(self._queue_ids(self.coord), ['PA-Q1'])


# ===========================================================================
# (d) APPROVE
# ===========================================================================

class ApproveTests(PmApprovalBase):

    def test_01_releases_stamps_and_writes_one_ledger_row(self):
        site, assignment = self._parked('PA-A1')
        self._login(self.pm)
        response = self.client.post(self._url('design_pm_approve', site),
                                    {'remark': 'Matches the survey'})
        self.assertRedirects(response, reverse('design_pm_approval_queue'),
                             fetch_redirect_response=False)

        assignment.refresh_from_db()
        self.assertEqual(assignment.status, DESIGN_RELEASED)
        self.assertIsNotNone(assignment.pm_approved_at)
        self.assertEqual(assignment.pm_approved_by, self.pm)
        # B4 as amended: the release stamp moves to the PM's approval.
        self.assertEqual(assignment.released_at, assignment.pm_approved_at)
        self.assertEqual(assignment.released_by, self.pm)

        rows = list(self._transitions(assignment))
        self.assertEqual(len(rows), 1)
        row = rows[0]
        self.assertEqual(row.from_status, DESIGN_AWAITING_PM_APPROVAL)
        self.assertEqual(row.to_status, DESIGN_RELEASED)
        self.assertEqual(row.reason_code, REASON_DESIGN_PM_APPROVED)
        self.assertEqual(row.remark, 'Matches the survey')
        self.assertEqual(row.actor, self.pm)

    def test_02_the_remark_is_optional(self):
        site, assignment = self._parked('PA-A2')
        self._login(self.pm)
        self.client.post(self._url('design_pm_approve', site), {})
        assignment.refresh_from_db()
        self.assertEqual(assignment.status, DESIGN_RELEASED)
        self.assertEqual(self._transitions(assignment).get().remark, '')

    def test_03_a_coordinator_may_approve(self):
        site, assignment = self._parked('PA-A3')
        site.coordinators.add(self.coord)
        self._login(self.coord)
        self.client.post(self._url('design_pm_approve', site), {})
        assignment.refresh_from_db()
        self.assertEqual(assignment.status, DESIGN_RELEASED)
        self.assertEqual(assignment.pm_approved_by, self.coord)
        self.assertEqual(assignment.released_by, self.coord)


# ===========================================================================
# (e) REJECT
# ===========================================================================

class RejectTests(PmApprovalBase):

    def test_01_returns_to_the_head_and_writes_nothing_else(self):
        site, assignment = self._site('PA-R1')
        Project.objects.filter(pk=site.pk).update(assigned_pm=self.pm)
        design_views._open_first_attempt(assignment)
        assignment.refresh_from_db()
        self._park_in_pm_gate(assignment)
        attempts_before = DesignAttempt.objects.filter(assignment=assignment).count()
        attempt_number_before = assignment.current_attempt_number

        self._login(self.pm)
        response = self.client.post(self._url('design_pm_reject', site),
                                    {'remark': 'Inverter make is not the tendered one'})
        self.assertRedirects(response, reverse('design_pm_approval_queue'),
                             fetch_redirect_response=False)

        assignment.refresh_from_db()
        self.assertEqual(assignment.status, DESIGN_PM_REJECTED)
        # NO attempt, NO approval stamp, NO release stamp.
        self.assertEqual(DesignAttempt.objects.filter(assignment=assignment).count(),
                         attempts_before)
        self.assertEqual(assignment.current_attempt_number, attempt_number_before)
        self.assertIsNone(assignment.pm_approved_at)
        self.assertIsNone(assignment.pm_approved_by_id)
        self.assertIsNone(assignment.released_at)
        self.assertIsNone(assignment.released_by_id)

        row = self._transitions(assignment).get()
        self.assertEqual(row.from_status, DESIGN_AWAITING_PM_APPROVAL)
        self.assertEqual(row.to_status, DESIGN_PM_REJECTED)
        self.assertEqual(row.reason_code, REASON_DESIGN_PM_REJECTED)
        self.assertEqual(row.remark, 'Inverter make is not the tendered one')
        self.assertEqual(row.actor, self.pm)

    def test_02_an_old_release_stamp_survives_a_rejection(self):
        """A reopened site keeps its old released_at (audit P2), so a parked site can carry
        one. The rejection must leave it exactly as it found it."""
        site, assignment = self._parked('PA-R2')
        stamp = timezone.now() - timedelta(days=30)
        DesignAssignment.objects.filter(pk=assignment.pk).update(
            released_at=stamp, released_by=self.head)
        self._login(self.pm)
        self.client.post(self._url('design_pm_reject', site), {'remark': 'Wrong tilt'})
        assignment.refresh_from_db()
        self.assertEqual(assignment.status, DESIGN_PM_REJECTED)
        self.assertEqual(assignment.released_at, stamp)
        self.assertEqual(assignment.released_by, self.head)


# ===========================================================================
# (f) A BLANK REMARK ON REJECT
# ===========================================================================

class BlankRemarkTests(PmApprovalBase):

    def test_01_blank_and_whitespace_are_refused_and_write_nothing(self):
        site, assignment = self._parked('PA-B1')
        self._login(self.pm)
        for remark in (None, '', '   \n\t '):
            data = {} if remark is None else {'remark': remark}
            response = self.client.post(self._url('design_pm_reject', site), data)
            self.assertRedirects(response, reverse('design_pm_approval_queue'),
                                 fetch_redirect_response=False)
            self.assertIn('a remark is required', self._messages(response))
            self._assert_untouched(assignment, DESIGN_AWAITING_PM_APPROVAL)


# ===========================================================================
# (g) REFUSALS
# ===========================================================================

class RefusalTests(PmApprovalBase):

    def test_01_both_views_refuse_any_other_status(self):
        for i, status in enumerate((DESIGN_IN_QC, DESIGN_AWAITING_HEAD_QC, DESIGN_RELEASED)):
            site, assignment = self._pm_site(f'PA-S{i}', status=status)
            self._login(self.pm)
            for name in ('design_pm_approve', 'design_pm_reject'):
                response = self.client.post(self._url(name, site), {'remark': 'x'})
                self.assertRedirects(response, reverse('design_pm_approval_queue'),
                                     fetch_redirect_response=False)
                self.assertIn('not awaiting your approval', self._messages(response))
                self._assert_untouched(assignment, status)

    def test_02_both_views_refuse_anyone_but_the_sites_pm_or_coordinator(self):
        site, assignment = self._parked('PA-U1')
        self._pm_site('PA-U2', pm=self.other_pm)
        for profile in (self.other_pm, self.coord, self.designer, self.head,
                        self.scm, self.finance):
            self._login(profile)
            for name in ('design_pm_approve', 'design_pm_reject'):
                response = self.client.post(self._url(name, site), {'remark': 'x'})
                self.assertEqual(response.status_code, 403, (profile.user.username, name))
                self.assertTrue(response.content.strip())
        self._assert_untouched(assignment, DESIGN_AWAITING_PM_APPROVAL)

    def test_03_a_get_writes_nothing(self):
        site, assignment = self._parked('PA-G1')
        self._login(self.pm)
        for name in ('design_pm_approve', 'design_pm_reject'):
            response = self.client.get(self._url(name, site))
            self.assertRedirects(response, reverse('design_pm_approval_queue'),
                                 fetch_redirect_response=False)
        self._assert_untouched(assignment, DESIGN_AWAITING_PM_APPROVAL)

    def test_04_an_unknown_site_is_404(self):
        self._login(self.pm)
        for name in ('design_pm_approve', 'design_pm_reject'):
            response = self.client.post(reverse(name, kwargs={'project_id': 'NO-SUCH'}))
            self.assertEqual(response.status_code, 404)


# ===========================================================================
# B3 — THE WORKSPACE READ
# ===========================================================================

class WorkspaceReadTests(PmApprovalBase):

    def _get(self, profile, site):
        self._login(profile)
        return self.client.get(self._url('design_site_workspace', site))

    def test_01_the_sites_pm_and_coordinator_read_it_while_parked(self):
        site, _ = self._parked('PA-W1')
        site.coordinators.add(self.coord)
        self.assertEqual(self._get(self.pm, site).status_code, 200)
        self.assertEqual(self._get(self.coord, site).status_code, 200)

    def test_02_the_pm_is_refused_at_every_other_status(self):
        for i, status in enumerate((DESIGN_IN_QC, DESIGN_AWAITING_HEAD_QC, DESIGN_RELEASED)):
            site, _ = self._pm_site(f'PA-W2-{i}', status=status)
            self.assertEqual(self._get(self.pm, site).status_code, 403)

    def test_03_another_pm_is_refused_even_while_parked(self):
        site, _ = self._parked('PA-W3')
        self._pm_site('PA-W3-OTHER', pm=self.other_pm)
        for profile in (self.other_pm, self.scm, self.finance):
            self.assertEqual(self._get(profile, site).status_code, 403)

    def test_04_the_designer_and_head_are_unchanged(self):
        site, _ = self._pm_site('PA-W4')
        self.assertEqual(self._get(self.designer, site).status_code, 200)
        self.assertEqual(self._get(self.head, site).status_code, 200)
