# Generated by Django 6.0.6 on 2026-06-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_superuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('PM', 'PM'), ('Site Engineer', 'Site Engineer'), ('Design', 'Design'), ('Finance', 'Finance'), ('SCM', 'SCM'), ('CEO', 'CEO')], max_length=20),
        ),
    ]
