# Generated by Django 6.0.6 on 2026-06-10 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='projects.userprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=10),
        ),
    ]
