# Generated by Django 6.0.6 on 2026-06-11 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_vendorcategory_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Acknowledged', 'Acknowledged'), ('Revision Requested', 'Revision Requested')], default='Draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boq', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_boqs', to='projects.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('category', models.CharField(choices=[('Solar Modules', 'Solar Modules'), ('Structure', 'Structure'), ('Inverter', 'Inverter'), ('BOS', 'BOS'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('uom', models.CharField(choices=[('Nos', 'Nos'), ('LOT', 'LOT'), ('Mtr', 'Mtr'), ('Pkt', 'Pkt'), ('LS', 'LS'), ('Sets', 'Sets'), ('Kg', 'Kg')], max_length=10)),
                ('boq_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_standard_item', models.BooleanField(default=True)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.boq')),
                ('make_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_items', to='projects.vendor')),
                ('ordered_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_items', to='projects.vendor')),
            ],
            options={
                'ordering': ['serial_no'],
            },
        ),
        migrations.CreateModel(
            name='BOQRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revised_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField()),
                ('reason', models.TextField()),
                ('snapshot', models.JSONField()),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.boq')),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.userprofile')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
