# Generated by Django 6.0.6 on 2026-06-11 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_design',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Design'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_projects', to='projects.userprofile'),
        ),
    ]
