# Generated by Django 6.0.6 on 2026-06-12 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_assigned_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commissioned_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_milestones', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('PM', 'PM'), ('Site Engineer', 'Site Engineer'), ('Design', 'Design'), ('Finance', 'Finance'), ('SCM', 'SCM'), ('CEO', 'CEO'), ('BD', 'BD')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=10)),
                ('milestone_description', models.CharField(default='', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance_reason', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Invoiced', 'Invoiced'), ('Received', 'Received')], default='Pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['milestone_name'],
            },
        ),
    ]
