# Generated by Django 6.0.6 on 2026-06-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_task_is_payment_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
