# Generated by Django 6.0.6 on 2026-06-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('message_api_sent', 'Sent by Interakt'), ('message_api_delivered', 'Delivered to Phone'), ('message_api_read', 'Read'), ('message_api_failed', 'Failed at Delivery')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='interakt_message_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
