# Generated by Django 6.0.6 on 2026-06-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_task_duration_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Sub Admin', 'Sub Admin'), ('PM', 'PM'), ('Site Engineer', 'Site Engineer'), ('Design', 'Design'), ('Finance', 'Finance'), ('SCM', 'SCM'), ('CEO', 'CEO'), ('BD', 'BD')], max_length=20),
        ),
    ]
