# Generated by Django 6.0.6 on 2026-06-30 04:13

from django.db import migrations, models


def rename_sub_admin_role(apps, schema_editor):
    UserProfile = apps.get_model('projects', 'UserProfile')
    UserProfile.objects.filter(role='Sub Admin').update(role='System Admin')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_alter_userprofile_role_add_subadmin'),
    ]

    operations = [
        migrations.RunPython(rename_sub_admin_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('System Admin', 'System Admin'), ('PM', 'PM'), ('Site Engineer', 'Site Engineer'), ('Design', 'Design'), ('Finance', 'Finance'), ('SCM', 'SCM'), ('CEO', 'CEO'), ('BD', 'BD')], max_length=20),
        ),
    ]
