# Generated by Django 6.0.6 on 2026-07-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_rename_subadmin_to_systemadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_site_engineer',
        ),
    ]
