# Generated by Django 6.0.6 on 2026-07-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_remove_assigned_site_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_design_head',
            field=models.BooleanField(default=False),
        ),
    ]
