# Generated by Django 6.0.6 on 2026-07-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_add_is_design_head_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coordinators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Project Coordinator'}, related_name='coordinated_projects', to='projects.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('System Admin', 'System Admin'), ('PM', 'PM'), ('Project Coordinator', 'Project Coordinator'), ('Site Engineer', 'Site Engineer'), ('Design', 'Design'), ('Finance', 'Finance'), ('SCM', 'SCM'), ('CEO', 'CEO'), ('BD', 'BD')], max_length=20),
        ),
    ]
