# Generated by Django 6.0.6 on 2026-07-14 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_project_coordinators_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_checked', models.BooleanField(default=False)),
                ('photo_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('photo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('photo_supabase_path', models.CharField(blank=True, default='', max_length=500)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='projects.task')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
