# Generated by Django 6.0.6 on 2026-07-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_reusable_checklists'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFieldEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('capacity_kw', 'Capacity (kW)'), ('contract_value', 'Contract Value'), ('target_commissioning_date', 'Target Commissioning Date')], max_length=32)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_edit_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
