# Generated by Django 6.0.6 on 2026-07-23 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_gantt_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('OPEX', 'OPEX'), ('CAPEX', 'CAPEX')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('In Progress', 'In Progress'), ('Commissioned', 'Commissioned'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('short_tender_code', models.CharField(blank=True, default='', max_length=20)),
                ('total_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Total planned capacity in MW (storage only).', max_digits=10, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('planned_site_count', models.PositiveIntegerField(blank=True, help_text='Target site count from the tender/contract. Informational ONLY — never enforced as a cap. The live actual count comes from the rollup.', null=True)),
                ('tender_reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('bid_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('ppa_reference', models.CharField(blank=True, default='', max_length=100)),
                ('ppa_signed_date', models.DateField(blank=True, null=True)),
                ('ppa_per_unit_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ppa_escalation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ppa_escalation_frequency', models.CharField(blank=True, default='', max_length=50)),
                ('financing_partner_name', models.CharField(blank=True, default='', max_length=200)),
                ('financing_assistance_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='projects.program'),
        ),
    ]
