# Generated by Django 6.0.6 on 2026-07-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_project_site_code_alter_project_project_id_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
    ]
