# Generated by Django 6.0.6 on 2026-07-27 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_boqitemmaster_boqitem_item_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='design_head_deputy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_for', to='projects.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('System Admin', 'System Admin'), ('PM', 'PM'), ('Project Coordinator', 'Project Coordinator'), ('Site Engineer', 'Site Engineer'), ('Design', 'Design'), ('Design Head', 'Design Head'), ('Finance', 'Finance'), ('SCM', 'SCM'), ('CEO', 'CEO'), ('BD', 'BD')], max_length=20),
        ),
        migrations.CreateModel(
            name='DesignAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_file_bucket', models.CharField(blank=True, default='', max_length=100)),
                ('survey_file_path', models.CharField(blank=True, default='', max_length=500)),
                ('survey_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('survey_returned_at', models.DateTimeField(blank=True, null=True)),
                ('survey_return_reason', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('current_attempt_number', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('awaiting_survey', 'Awaiting survey'), ('survey_returned', 'Survey returned'), ('awaiting_allocation', 'Awaiting allocation'), ('allocated', 'Allocated'), ('due_date_proposed', 'Due date proposed'), ('in_design', 'In design'), ('arka_submitted', 'Arka submitted'), ('arka_rejected', 'Arka rejected'), ('artifacts_uploaded', 'Artifacts uploaded'), ('in_qc', 'In QC'), ('qc_failed', 'QC failed'), ('released', 'Released')], default='awaiting_survey', max_length=30)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_design_assignments', to='projects.userprofile')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_assignments', to='projects.userprofile')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_assignment', to='projects.project')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_design_assignments', to='projects.userprofile')),
                ('survey_returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_design_surveys', to='projects.userprofile')),
                ('survey_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_design_surveys', to='projects.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('opened_reason', models.CharField(choices=[('initial', 'Initial'), ('qc_failed', 'QC failed'), ('pm_change_request', 'PM change request')], default='initial', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('qc_verdict', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('qc_remarks', models.TextField(blank=True, default='')),
                ('qc_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('qc_started_at', models.DateTimeField(blank=True, null=True)),
                ('boq_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='projects.designassignment')),
                ('boq_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_submitted_attempts', to='projects.userprofile')),
                ('qc_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_reviewed_attempts', to='projects.userprofile')),
            ],
            options={
                'ordering': ['assignment', 'attempt_number'],
                'unique_together': {('assignment', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='ArkaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('capacity_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arka_link', models.URLField(max_length=1000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_arka_submissions', to='projects.userprofile')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arka_submissions', to='projects.userprofile')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arka_submissions', to='projects.designattempt')),
            ],
            options={
                'ordering': ['attempt', 'version'],
            },
        ),
        migrations.CreateModel(
            name='DesignChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='projects.designattempt')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='design_change_requests', to='projects.userprofile')),
                ('resulting_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_by_change_request', to='projects.designattempt')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cad_pdf', 'CAD (PDF)'), ('cad_dwg', 'CAD (DWG)'), ('boq_excel', 'BOQ (Excel)'), ('boq_pdf', 'BOQ (PDF)')], max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('bucket', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_files', to='projects.designattempt')),
                ('derived_from_arka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derived_files', to='projects.arkasubmission')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='projects.designfile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_design_files', to='projects.userprofile')),
            ],
            options={
                'ordering': ['attempt', 'kind', 'version'],
            },
        ),
        migrations.CreateModel(
            name='DueDateCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField()),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_due_dates', to='projects.userprofile')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_date_commitments', to='projects.designassignment')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_due_dates', to='projects.userprofile')),
            ],
            options={
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='arkasubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('attempt',), name='uniq_current_arka_per_attempt'),
        ),
        migrations.AlterUniqueTogether(
            name='arkasubmission',
            unique_together={('attempt', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='designfile',
            unique_together={('attempt', 'kind', 'version')},
        ),
        migrations.AddConstraint(
            model_name='duedatecommitment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('assignment',), name='uniq_current_due_date_per_assignment'),
        ),
    ]
