# Generated by Django 6.0.6 on 2026-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_userprofile_design_head_deputy_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='arkasubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verdict', 'rejected'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='rejection_reason_required_when_rejected'),
        ),
        migrations.AddConstraint(
            model_name='designattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('qc_verdict', 'failed'), _negated=True), models.Q(('qc_remarks', ''), _negated=True), _connector='OR'), name='qc_remarks_required_when_qc_failed'),
        ),
    ]
