# Generated by Django 6.0.6 on 2026-07-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_arkasubmission_rejection_reason_required_when_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designassignment',
            name='status',
            field=models.CharField(choices=[('awaiting_survey', 'Awaiting survey'), ('awaiting_allocation', 'Awaiting allocation'), ('allocated', 'Allocated'), ('due_date_proposed', 'Due date proposed'), ('in_design', 'In design'), ('arka_submitted', 'Arka submitted'), ('arka_rejected', 'Arka rejected'), ('artifacts_uploaded', 'Artifacts uploaded'), ('in_qc', 'In QC'), ('qc_failed', 'QC failed'), ('released', 'Released'), ('survey_returned', 'Blocked — survey inadequate')], default='awaiting_survey', max_length=30),
        ),
    ]
