# Generated by Django 6.0.6 on 2026-07-28 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_backfill_opex_assigned_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_site_groups', to='projects.userprofile')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_site_groups', to='projects.userprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_groups', to='projects.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.TextField(blank=True, default='')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_group_memberships', to='projects.userprofile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.sitegroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='projects.project')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_group_memberships', to='projects.userprofile')),
            ],
            options={
                'ordering': ['added_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('project',), name='uniq_active_site_group_membership')],
            },
        ),
    ]
