# Generated by Django 6.0.6 on 2026-07-28 11:06
"""Remove 'Design Head' from UserProfile.ROLE_CHOICES (Part 6.5b).

CHOICES ONLY — NO DATA OPERATION, AND NONE IS NEEDED. Zero users hold the role on
either database: confirmed on local (`filter(role='Design Head').count() == 0`) and
confirmed personally by the product owner on production. `choices` is not enforced at
the database level, so this alters no column and rewrites no row; on Postgres it is a
no-op state change.

Reversible: re-applying 0048's field definition restores the choice. If this is ever
reversed, read DESIGN_HEAD_ROLE_MIGRATION_AUDIT.md first — the role was removed on
purpose, not abandoned. See the note in models.UserProfile.ROLE_CHOICES.

`is_design_head` and `design_head_deputy` are untouched by this migration and remain
the design module's authority mechanism.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_sitegroup_sitegroupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('System Admin', 'System Admin'), ('PM', 'PM'), ('Project Coordinator', 'Project Coordinator'), ('Site Engineer', 'Site Engineer'), ('Design', 'Design'), ('Finance', 'Finance'), ('SCM', 'SCM'), ('CEO', 'CEO'), ('BD', 'BD')], max_length=20),
        ),
    ]
