# Generated by Django 6.0.6 on 2026-07-29 11:33
"""Part 8 — CAD zip upload and the Design Hold rename.

THERE IS NO DATA OPERATION HERE, and that is deliberate on all three counts:

  AddField archive_listing   default=list, so every existing DesignFile row gets []
                             without a backfill. An empty listing on a legacy
                             cad_pdf/cad_dwg row reads as "not an archive", which is
                             true.

  AlterField status          LABEL ONLY. The stored value stays `survey_returned`.
                             There has never been a stored string `blocked` in this
                             column, so "Blocked" -> "Design Hold" cannot touch a row.

  AlterField kind            Adds `cad_zip` and re-labels `cad_pdf`/`cad_dwg` as
                             legacy. The two legacy values are KEPT, not migrated and
                             not deleted — rows already carry them and must stay
                             readable. Dropping them would break get_kind_display()
                             and full_clean() on every one of those rows.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='designfile',
            name='archive_listing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='designassignment',
            name='status',
            field=models.CharField(choices=[('awaiting_survey', 'Awaiting survey'), ('awaiting_allocation', 'Awaiting allocation'), ('allocated', 'Allocated'), ('due_date_proposed', 'Due date proposed'), ('in_design', 'In design'), ('arka_submitted', 'Arka submitted'), ('arka_rejected', 'Arka rejected'), ('artifacts_uploaded', 'Artifacts uploaded'), ('in_qc', 'In QC'), ('qc_failed', 'QC failed'), ('released', 'Released'), ('survey_returned', 'Design Hold — survey inadequate')], default='awaiting_survey', max_length=30),
        ),
        migrations.AlterField(
            model_name='designfile',
            name='kind',
            field=models.CharField(choices=[('cad_zip', 'CAD (zip)'), ('boq_excel', 'BOQ (Excel)'), ('boq_pdf', 'BOQ (PDF)'), ('cad_pdf', 'CAD (PDF) — legacy'), ('cad_dwg', 'CAD (DWG) — legacy')], max_length=20),
        ),
    ]
