# Generated by Django 6.0.6 on 2026-07-29 17:14
#
# PART 9 — the second review gate.
#
# THE BACKFILL AT THE BOTTOM OF THIS FILE IS THE PART THAT NEEDS EXPLAINING.
#
# Part 9 narrows the meaning of the EXISTING verdict fields from "the review" to "the
# FIRST review", and adds head_* for the second. Every verdict recorded before this
# migration was recorded under the one-gate rule, by the Design Head himself. Left alone,
# those rows would say the Head had not reviewed work he personally reviewed — and,
# worse, the CAD/BOQ gate moves to head_verdict='approved', so any site sitting at
# arka_submitted with an approved Arka would lose the ability to upload CAD mid-flight.
#
# So the positive outcomes are carried forward:
#
#     ArkaSubmission  verdict='approved' -> head_verdict='approved'
#     DesignAttempt   qc_verdict='passed' -> head_verdict='passed'
#
# and NOTHING ELSE IS TOUCHED. Three consequences worth stating, because each was a
# choice and not an oversight:
#
#   * REJECTIONS AND FAILURES ARE NOT CARRIED FORWARD. Under the new flow a QC rejection
#     ends the Arka version and a QC failure closes the attempt — the Head never sees
#     either. head_verdict='pending' on those rows is therefore not a gap, it is the
#     correct statement that the second gate never ran. It also means the new CHECK
#     constraints are satisfiable without inventing rejection reasons or remarks that
#     nobody wrote.
#
#   * head_reviewed_by IS LEFT NULL. Copying the original reviewer would manufacture rows
#     in which one person recorded BOTH verdicts — precisely what settled decision 2
#     exists to forbid — and would let a future per-reviewer quality report read a
#     historical self-confirmation as a clean second-gate record. Null is the honest
#     answer: the gate was satisfied, and no second person satisfied it.
#
#   * head_reviewed_at IS COPIED. The timestamp is a fact about when the artifact cleared
#     review, and losing it would leave a hole in the timeline for no benefit.
#
# head_overturned_qc stays False everywhere, which is correct: one gate cannot disagree
# with itself.
#
# The reverse is a genuine inverse — it clears exactly the columns the forward pass set,
# so `migrate projects 0054` followed by `migrate projects 0055` returns the same rows.

import django.db.models.deletion
from django.db import migrations, models


def carry_forward_single_gate_verdicts(apps, schema_editor):
    """Positive pre-Part-9 verdicts satisfy the new Head gate. See the note above."""
    ArkaSubmission = apps.get_model('projects', 'ArkaSubmission')
    DesignAttempt  = apps.get_model('projects', 'DesignAttempt')

    # F-expression rather than a Python loop: this is one UPDATE per table regardless of
    # row count, and the source column is the only thing being read.
    ArkaSubmission.objects.filter(verdict='approved').update(
        head_verdict='approved',
        head_reviewed_at=models.F('reviewed_at'),
    )
    DesignAttempt.objects.filter(qc_verdict='passed').update(
        head_verdict='passed',
        head_reviewed_at=models.F('qc_reviewed_at'),
    )


def clear_carried_forward_verdicts(apps, schema_editor):
    """Reverse of the above. The head_* columns are dropped by the AddField reversals
    immediately after this runs, so this exists to make the RunPython reversible in its
    own right rather than to leave a particular state behind."""
    ArkaSubmission = apps.get_model('projects', 'ArkaSubmission')
    DesignAttempt  = apps.get_model('projects', 'DesignAttempt')

    ArkaSubmission.objects.update(head_verdict='pending', head_reviewed_at=None)
    DesignAttempt.objects.update(head_verdict='pending', head_reviewed_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_part8_cad_zip_and_design_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='arkasubmission',
            name='head_failure_category',
            field=models.CharField(blank=True, choices=[('Designer execution', [('layout_error', 'Layout error: module placement, row spacing, orientation'), ('shading', 'Shading or obstruction not accounted for'), ('capacity_error', 'Capacity error: designed capacity wrong for available area'), ('structural_constraint', 'Roof or structural constraint violated'), ('access_setback', 'Access, walkway, or setback non-compliance'), ('structural_design', 'Structural design error: foundation, mounting, wind load'), ('electrical_design', 'Electrical design error: string sizing, inverter matching, cable sizing'), ('earthing_lightning', 'Earthing or lightning protection error'), ('drawing_incomplete', 'Drawing incomplete: missing views, dimensions, annotations'), ('standards', 'Standards non-compliance: MNRE, IS, DISCOM norms'), ('boq_quantity', 'BOQ quantity error'), ('boq_specification', 'BOQ item or specification error')]), ('Input problem — not designer rework', [('survey_inadequate', 'Survey data inadequate or incorrect'), ('site_differs', 'Site conditions differ from survey')]), ('Brief change — not designer rework', [('requirement_changed', 'Client or PM requirement changed'), ('scope_revised', 'Scope or capacity revised after design started')])], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='arkasubmission',
            name='head_overturned_qc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arkasubmission',
            name='head_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='arkasubmission',
            name='head_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arkasubmission',
            name='head_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_reviewed_arka_submissions', to='projects.userprofile'),
        ),
        migrations.AddField(
            model_name='arkasubmission',
            name='head_verdict',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='arkasubmission',
            name='qc_failure_category',
            field=models.CharField(blank=True, choices=[('Designer execution', [('layout_error', 'Layout error: module placement, row spacing, orientation'), ('shading', 'Shading or obstruction not accounted for'), ('capacity_error', 'Capacity error: designed capacity wrong for available area'), ('structural_constraint', 'Roof or structural constraint violated'), ('access_setback', 'Access, walkway, or setback non-compliance'), ('structural_design', 'Structural design error: foundation, mounting, wind load'), ('electrical_design', 'Electrical design error: string sizing, inverter matching, cable sizing'), ('earthing_lightning', 'Earthing or lightning protection error'), ('drawing_incomplete', 'Drawing incomplete: missing views, dimensions, annotations'), ('standards', 'Standards non-compliance: MNRE, IS, DISCOM norms'), ('boq_quantity', 'BOQ quantity error'), ('boq_specification', 'BOQ item or specification error')]), ('Input problem — not designer rework', [('survey_inadequate', 'Survey data inadequate or incorrect'), ('site_differs', 'Site conditions differ from survey')]), ('Brief change — not designer rework', [('requirement_changed', 'Client or PM requirement changed'), ('scope_revised', 'Scope or capacity revised after design started')])], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='designattempt',
            name='head_failure_category',
            field=models.CharField(blank=True, choices=[('Designer execution', [('layout_error', 'Layout error: module placement, row spacing, orientation'), ('shading', 'Shading or obstruction not accounted for'), ('capacity_error', 'Capacity error: designed capacity wrong for available area'), ('structural_constraint', 'Roof or structural constraint violated'), ('access_setback', 'Access, walkway, or setback non-compliance'), ('structural_design', 'Structural design error: foundation, mounting, wind load'), ('electrical_design', 'Electrical design error: string sizing, inverter matching, cable sizing'), ('earthing_lightning', 'Earthing or lightning protection error'), ('drawing_incomplete', 'Drawing incomplete: missing views, dimensions, annotations'), ('standards', 'Standards non-compliance: MNRE, IS, DISCOM norms'), ('boq_quantity', 'BOQ quantity error'), ('boq_specification', 'BOQ item or specification error')]), ('Input problem — not designer rework', [('survey_inadequate', 'Survey data inadequate or incorrect'), ('site_differs', 'Site conditions differ from survey')]), ('Brief change — not designer rework', [('requirement_changed', 'Client or PM requirement changed'), ('scope_revised', 'Scope or capacity revised after design started')])], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='designattempt',
            name='head_overturned_qc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designattempt',
            name='head_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='designattempt',
            name='head_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designattempt',
            name='head_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_reviewed_attempts', to='projects.userprofile'),
        ),
        migrations.AddField(
            model_name='designattempt',
            name='head_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designattempt',
            name='head_verdict',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='designattempt',
            name='qc_failure_category',
            field=models.CharField(blank=True, choices=[('Designer execution', [('layout_error', 'Layout error: module placement, row spacing, orientation'), ('shading', 'Shading or obstruction not accounted for'), ('capacity_error', 'Capacity error: designed capacity wrong for available area'), ('structural_constraint', 'Roof or structural constraint violated'), ('access_setback', 'Access, walkway, or setback non-compliance'), ('structural_design', 'Structural design error: foundation, mounting, wind load'), ('electrical_design', 'Electrical design error: string sizing, inverter matching, cable sizing'), ('earthing_lightning', 'Earthing or lightning protection error'), ('drawing_incomplete', 'Drawing incomplete: missing views, dimensions, annotations'), ('standards', 'Standards non-compliance: MNRE, IS, DISCOM norms'), ('boq_quantity', 'BOQ quantity error'), ('boq_specification', 'BOQ item or specification error')]), ('Input problem — not designer rework', [('survey_inadequate', 'Survey data inadequate or incorrect'), ('site_differs', 'Site conditions differ from survey')]), ('Brief change — not designer rework', [('requirement_changed', 'Client or PM requirement changed'), ('scope_revised', 'Scope or capacity revised after design started')])], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_design_qc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='designassignment',
            name='status',
            field=models.CharField(choices=[('awaiting_survey', 'Awaiting survey'), ('awaiting_allocation', 'Awaiting allocation'), ('allocated', 'Allocated'), ('due_date_proposed', 'Due date proposed'), ('in_design', 'In design'), ('arka_submitted', 'Arka submitted'), ('awaiting_head_arka', 'Arka — awaiting Design Head'), ('arka_rejected', 'Arka rejected'), ('artifacts_uploaded', 'Artifacts uploaded'), ('in_qc', 'In QC'), ('awaiting_head_qc', 'QC passed — awaiting Design Head'), ('qc_failed', 'QC failed'), ('released', 'Released'), ('survey_returned', 'Design Hold — survey inadequate')], default='awaiting_survey', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='arkasubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('head_verdict', 'rejected'), _negated=True), models.Q(('head_rejection_reason', ''), _negated=True), _connector='OR'), name='head_rejection_reason_required_when_head_rejected'),
        ),
        migrations.AddConstraint(
            model_name='designattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('head_verdict', 'failed'), _negated=True), models.Q(('head_remarks', ''), _negated=True), _connector='OR'), name='head_remarks_required_when_head_failed'),
        ),
        # Runs LAST, after both constraints exist — the backfill writes only 'approved'
        # and 'passed', so it can never trip a constraint that guards 'rejected' and
        # 'failed'. Ordering it here rather than earlier means the constraints are proven
        # against the backfilled data rather than against an empty column.
        migrations.RunPython(
            carry_forward_single_gate_verdicts,
            clear_carried_forward_verdicts,
        ),
    ]
