# Generated by Django 6.0.6 on 2026-08-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_part9_design_qc_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='arkasubmission',
            name='carried_forward_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_forward_to', to='projects.arkasubmission'),
        ),
        migrations.AddField(
            model_name='designattempt',
            name='redo_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='designfile',
            name='carried_forward_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_forward_to', to='projects.designfile'),
        ),
    ]
