# Generated by Django 6.0.6 on 2026-08-05 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_part10_design_analytics_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='designassignment',
            name='survey_folder_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='designassignment',
            name='survey_link_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designassignment',
            name='survey_link_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_design_surveys', to='projects.userprofile'),
        ),
    ]
