# Generated by Django 6.0.6 on 2026-08-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_designassignment_survey_folder_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arkasubmission',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='designfile',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
