# Generated by Django 6.0.6 on 2026-08-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_arkasubmission_remarks_designfile_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='designattempt',
            name='boq_remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
