# Generated by Django 6.0.6 on 2026-08-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_designattempt_boq_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='designassignment',
            name='qc_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designassignment',
            name='qc_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_qc_design_assignments', to='projects.userprofile'),
        ),
        migrations.AddField(
            model_name='designassignment',
            name='qc_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_design_assignments', to='projects.userprofile'),
        ),
    ]
