# Generated by Django 6.0.6 on 2026-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_designassignment_qc_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitemmaster',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
