# Generated by Django 6.0.6 on 2026-08-28 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_boqitemmaster_is_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('project', 'Project'), ('task', 'Task'), ('boq', 'BOQ'), ('delivery_challan', 'Delivery Challan'), ('issue', 'Issue'), ('payment_milestone', 'Payment Milestone')], db_index=True, max_length=30)),
                ('subject_id', models.PositiveIntegerField()),
                ('from_status', models.CharField(blank=True, default='', max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('actor_role_code', models.CharField(max_length=30)),
                ('reason_code', models.CharField(blank=True, default='', max_length=40)),
                ('remark', models.TextField(blank=True, default='')),
                ('client_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_transitions', to='projects.userprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_transitions', to='projects.project')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id', 'occurred_at'], name='sttrans_subject_idx'), models.Index(fields=['project', 'occurred_at'], name='sttrans_project_idx')],
            },
        ),
    ]
