# Generated by Django 6.0.6 on 2026-08-28 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_statustransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('Residential', 'Residential'), ('OPEX', 'OPEX'), ('CAPEX', 'CAPEX')], max_length=20)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplatePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.tasktemplate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField()),
                ('assigned_role', models.CharField(choices=[('PM', 'PM'), ('Site Engineer', 'Site Engineer'), ('Finance', 'Finance'), ('SCM', 'SCM'), ('BD / Sales', 'BD / Sales'), ('Design', 'Design')], default='PM', max_length=20)),
                ('task_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=10)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('is_payment_milestone', models.BooleanField(default=False)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.tasktemplatephase')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='template_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.tasktemplatetask'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['project_type', 'status'], name='tasktmpl_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(fields=('code', 'version_no'), name='uniq_task_template_code_version'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('code',), name='uniq_active_task_template_per_code'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplatephase',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='uniq_task_template_phase_code'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplatetask',
            constraint=models.UniqueConstraint(fields=('phase', 'code'), name='uniq_task_template_task_code'),
        ),
    ]
