# Generated by Django 6.0.6 on 2026-08-29, then reordered by hand and given the
# backfill below. Prompt 1.1a — the schema half of D-1. No behaviour changes with it.

from django.db import migrations, models


def backfill_membership_group_type(apps, schema_editor):
    """Stamp every existing membership 'procurement'.

    STRICTLY REDUNDANT AGAINST THE COLUMN DEFAULT, AND KEPT ANYWAY. AddField has already
    written 'procurement' into every existing row by the time this runs, so this updates
    nothing. It is here so the history STATES the intent rather than relying on a future
    reader noticing a default three operations up: every membership that existed before
    D-1 is an SCM procurement batch, and that is a claim about the business, not about a
    field's default value.

    NO EQUIVALENT PASS OVER SiteGroup, deliberately. The audit traced every creation path
    and found `design_views.site_group_create` to be the only production writer, so every
    existing group is a procurement batch by construction. The default covers it.
    """
    SiteGroupMembership = apps.get_model('projects', 'SiteGroupMembership')
    SiteGroupMembership.objects.update(group_type='procurement')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_checklist_drop_is_active'),
    ]

    operations = [
        # 1-2. The columns first — the new constraint is written over one of them.
        migrations.AddField(
            model_name='sitegroup',
            name='group_type',
            field=models.CharField(
                choices=[('procurement', 'Procurement'), ('execution', 'Execution')],
                default='procurement', max_length=12),
        ),
        migrations.AddField(
            model_name='sitegroupmembership',
            name='group_type',
            field=models.CharField(
                choices=[('procurement', 'Procurement'), ('execution', 'Execution')],
                default='procurement', max_length=12),
        ),

        # 3. The intent, stated. Reverse is a noop: unstamping would mean inventing a
        #    value, and the column is dropped by the reverse of the AddField above.
        migrations.RunPython(
            backfill_membership_group_type, migrations.RunPython.noop),

        # 4-5. Swap the exclusivity key from (project) to (project, group_type). Old one
        #      goes first: while both exist the old one is the stricter of the two and
        #      would refuse the very rows the new one is meant to admit.
        #
        #      REVERSIBILITY: this is reversible ONLY while no project holds two live
        #      memberships — which is every database until the execution feature is used.
        #      See docs/execution-model.md §12 for the full rollback position.
        migrations.RemoveConstraint(
            model_name='sitegroupmembership',
            name='uniq_active_site_group_membership',
        ),
        migrations.AddConstraint(
            model_name='sitegroupmembership',
            constraint=models.UniqueConstraint(
                condition=models.Q(('removed_at__isnull', True)),
                fields=('project', 'group_type'),
                name='uniq_active_site_group_membership_per_type'),
        ),
    ]
