# Generated by Django 6.0.6 on 2026-08-29 19:02
#
# Execution 1.2a. ENTIRELY ADDITIVE — three new columns that default False, one new
# table, and one CHECK. No RunPython and nothing to backfill: the flags default False,
# no warehouse exists yet, and no SiteGroup row can violate the constraint because
# `group_type` was born in 0071 with default 'procurement' and no writer sets anything
# else.
#
# HAND-ADJUSTED IN ONE RESPECT: makemigrations emitted `keeper` as a separate AddField
# after CreateModel, which is what the autodetector always does with a model's outbound
# FKs. It has been folded back into CreateModel — projects.userprofile predates this
# migration by seventy revisions, so there is no circular dependency that split was
# avoiding, and one CREATE TABLE is both what actually runs and what reads honestly.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_site_group_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keeper_of', to='projects.userprofile')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_hse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_qaqc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_warehouse_keeper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='sitegroup',
            constraint=models.CheckConstraint(condition=models.Q(('group_type', 'execution'), ('status', 'locked'), _negated=True), name='execution_groups_are_never_locked'),
        ),
    ]
