# Generated by Django 6.0.6 on 2026-08-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_execution_capability_flags_and_stock_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='projects.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects.task')),
            ],
            options={
                'verbose_name': 'task dependency',
                'verbose_name_plural': 'task dependencies',
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor'), name='uniq_task_dependency'), models.CheckConstraint(condition=models.Q(('predecessor', models.F('successor')), _negated=True), name='task_dependency_not_self')],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateTaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='projects.tasktemplatetask')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects.tasktemplatetask')),
            ],
            options={
                'verbose_name': 'task template task dependency',
                'verbose_name_plural': 'task template task dependencies',
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor'), name='uniq_task_template_task_dependency'), models.CheckConstraint(condition=models.Q(('predecessor', models.F('successor')), _negated=True), name='task_template_task_dependency_not_self')],
            },
        ),
    ]
