# Generated by Django 6.0.6 on 2026-08-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_task_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_mirror',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tasktemplatetask',
            name='is_mirror',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_role',
            field=models.CharField(choices=[('PM', 'PM'), ('Site Engineer', 'Site Engineer'), ('Finance', 'Finance'), ('SCM', 'SCM'), ('BD / Sales', 'BD / Sales'), ('Design', 'Design'), ('Project Coordinator', 'Project Coordinator')], default='PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktemplatetask',
            name='assigned_role',
            field=models.CharField(choices=[('PM', 'PM'), ('Site Engineer', 'Site Engineer'), ('Finance', 'Finance'), ('SCM', 'SCM'), ('BD / Sales', 'BD / Sales'), ('Design', 'Design'), ('Project Coordinator', 'Project Coordinator')], default='PM', max_length=20),
        ),
    ]
