# Generated by Django 6.0.6 on 2026-09-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_design_assignment_subject_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Waived', 'Waived')], default='Open', max_length=10)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('waiver_reason', models.TextField(blank=True, default='')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_punch_points', to='projects.userprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_points', to='projects.task')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_punch_points', to='projects.userprofile')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
