# Generated by Django 6.0.6 on 2026-09-06 03:53
#
# SCM pilot — warehouses on the delivery challan. ENTIRELY ADDITIVE: three nullable/
# defaulted columns on stocklocation and one nullable FK on deliverychallan. No
# RunPython, no backfill, and NOT ONE EXISTING ROW IS READ OR WRITTEN — the two
# CharFields default '', is_central defaults False, and issued_from_warehouse is NULL
# on every challan that already exists, which is the honest value for a challan raised
# before the column existed.
#
# The FK is PROTECT, so this migration also makes StockLocation undeletable once any
# challan points at it. That is deliberate and is the reason the column is here at all
# — see the field comment on DeliveryChallan.issued_from_warehouse.
#
# NOTHING IS SEEDED, and nothing here may ever seed. StockLocation's section note in
# models.py forbids it and tests_capability_flags.test_nothing_is_seeded enforces it:
# the three warehouses Horizon runs today are the product owner's data to enter, and
# baking them into the migration chain is what "the count must not be structural"
# rules out.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_checklist_answer_remarks_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='issued_from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='projects.stocklocation'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='is_central',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
