# Generated by Django 6.0.6 on 2026-09-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_deliverychallan_issued_from_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitemmaster',
            name='project_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('OPEX', 'RESCO'), ('CAPEX', 'CAPEX')], db_index=True, default='Residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklisttasklink',
            name='project_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('OPEX', 'RESCO'), ('CAPEX', 'CAPEX')], max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('OPEX', 'RESCO'), ('CAPEX', 'CAPEX')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('OPEX', 'RESCO'), ('CAPEX', 'CAPEX')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='project_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('OPEX', 'RESCO'), ('CAPEX', 'CAPEX')], max_length=20),
        ),
    ]
