"""Split site capacity into AC and DC; add IVRS, site name and coordinates.

HAND-WRITTEN, NOT AUTOGENERATED, AND THAT IS DELIBERATE. `makemigrations` asks
"did you rename capacity_kw to ac_capacity_kw?" BEFORE it asks about
dc_capacity_kw, because the added fields are considered alphabetically and
ac_capacity_kw carries the identical DecimalField(6, 2) signature. Answering that
prompt carelessly hands every existing capacity value to the AC column and leaves
DC blank — the exact inversion this change must not make. The RenameField below
names its target explicitly so there is nothing left to guess.

WHAT THIS DOES NOT CONTAIN: no RemoveField, no RunPython, no data migration. The
rename PRESERVES every stored value (RenameField is an ALTER TABLE ... RENAME
COLUMN; the column and its contents survive intact) and those values are now read
as DC. ac_capacity_kw lands null on every existing row and needs backfilling by
the team — see EXECUTION_MODULE_DEFERRED.md.

The AlterField at the end is on ProjectFieldEditLog.field_name and changes its
`choices` only, never its type or its data. Log rows written before this migration
keep field_name='capacity_kw', which is what the field was called when those edits
happened; nothing rewrites them, because that is what an audit trail is for.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_alter_boqitemmaster_project_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='capacity_kw',
            new_name='dc_capacity_kw',
        ),
        migrations.AddField(
            model_name='project',
            name='ac_capacity_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ivrs_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='projectfieldeditlog',
            name='field_name',
            field=models.CharField(
                choices=[
                    ('dc_capacity_kw', 'DC Capacity (kWp)'),
                    ('contract_value', 'Contract Value'),
                    ('target_commissioning_date', 'Target Commissioning Date'),
                ],
                max_length=32,
            ),
        ),
    ]
