# Generated by Django 6.0.6 on 2026-09-13 02:31
"""Add the design PM-rejected status, its attempt reason, and the Design Head's
classification of a PM rejection — ALL UNREACHABLE.

NOTHING WRITES THE STATUS, THE REASON OR EITHER FIELD. The transitions are prompt 3.1b-2b.
No RunPython, no data touched:
  * two AlterFields on `choices` only — no type, width or constraint change, so on
    PostgreSQL both are no-ops at the SQL level;
  * two AddFields, NOT NULL with default '' — every existing row lands '' in both;
  * one AddConstraint, validated by PostgreSQL against every existing row. It is the
    implication "a category requires remarks", in the shape of
    head_remarks_required_when_head_failed. Every existing row has a blank category, so
    its first term is true (R-1 pre-flight A1: 0 of 10 rows violating; the first draft's
    ~Q(category='') | ~Q(remarks='') violated all 10).

Generated by makemigrations and diffed against the R-1-approved text before it was applied.
The only differences were two choice VALUES the approved text had guessed from constant
names ('layout' and 'capacity'; the real values are 'layout_error' and 'capacity_error') —
this file is correct, the approved text was not — plus the order makemigrations emits the
five operations in.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0085_designassignment_pm_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='designattempt',
            name='pm_rejection_category',
            field=models.CharField(blank=True, choices=[('Designer execution', [('layout_error', 'Layout error: module placement, row spacing, orientation'), ('shading', 'Shading or obstruction not accounted for'), ('capacity_error', 'Capacity error: designed capacity wrong for available area'), ('structural_constraint', 'Roof or structural constraint violated'), ('access_setback', 'Access, walkway, or setback non-compliance'), ('structural_design', 'Structural design error: foundation, mounting, wind load'), ('electrical_design', 'Electrical design error: string sizing, inverter matching, cable sizing'), ('earthing_lightning', 'Earthing or lightning protection error'), ('drawing_incomplete', 'Drawing incomplete: missing views, dimensions, annotations'), ('standards', 'Standards non-compliance: MNRE, IS, DISCOM norms'), ('boq_quantity', 'BOQ quantity error'), ('boq_specification', 'BOQ item or specification error')]), ('Input problem — not designer rework', [('survey_inadequate', 'Survey data inadequate or incorrect'), ('site_differs', 'Site conditions differ from survey')]), ('Brief change — not designer rework', [('requirement_changed', 'Client or PM requirement changed'), ('scope_revised', 'Scope or capacity revised after design started')])], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='designattempt',
            name='pm_rejection_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='designassignment',
            name='status',
            field=models.CharField(choices=[('awaiting_survey', 'Awaiting survey'), ('awaiting_allocation', 'Awaiting allocation'), ('allocated', 'Allocated'), ('due_date_proposed', 'Due date proposed'), ('in_design', 'In design'), ('arka_submitted', 'Arka submitted'), ('awaiting_head_arka', 'Arka — awaiting Design Head'), ('arka_rejected', 'Arka rejected'), ('artifacts_uploaded', 'Artifacts uploaded'), ('in_qc', 'In QC'), ('awaiting_head_qc', 'QC passed — awaiting Design Head'), ('qc_failed', 'QC failed'), ('pm_rejected', 'PM rejected — awaiting Design Head'), ('awaiting_pm_approval', 'Awaiting PM approval'), ('released', 'Released'), ('survey_returned', 'Design Hold — survey inadequate')], default='awaiting_survey', max_length=30),
        ),
        migrations.AlterField(
            model_name='designattempt',
            name='opened_reason',
            field=models.CharField(choices=[('initial', 'Initial'), ('qc_failed', 'QC failed'), ('pm_change_request', 'PM change request'), ('pm_rejected', 'PM rejected')], default='initial', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='designattempt',
            constraint=models.CheckConstraint(condition=models.Q(('pm_rejection_category', ''), models.Q(('pm_rejection_remarks', ''), _negated=True), _connector='OR'), name='pm_rejection_remarks_required_with_category'),
        ),
    ]
