# Generated by Django 6.0.6 on 2026-09-20 11:15
#
# On-behalf receipt on the delivery challan line. ENTIRELY ADDITIVE: two defaulted
# columns on dclineitem and one CHECK constraint over them. No RunPython, no backfill,
# and NOT ONE EXISTING ROW IS READ OR WRITTEN — grn_on_behalf defaults False and
# grn_on_behalf_reason defaults '', which is the honest value for every receipt
# recorded before the distinction existed, and every such row satisfies
# ~Q(grn_on_behalf=True, grn_on_behalf_reason='') on the False leg. The constraint is
# therefore creatable against a populated table with no prior clean-up.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0086_design_pm_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='dclineitem',
            name='grn_on_behalf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dclineitem',
            name='grn_on_behalf_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='dclineitem',
            constraint=models.CheckConstraint(condition=models.Q(('grn_on_behalf', True), ('grn_on_behalf_reason', ''), _negated=True), name='grn_on_behalf_requires_reason'),
        ),
    ]
