# Generated by Django 6.0.6 on 2026-09-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0087_grn_on_behalf'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_self_certified',
            field=models.BooleanField(default=False),
        ),
    ]
