# Generated by Django 6.0.6 on 2026-09-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_task_approval_self_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_not_applicable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='not_applicable_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='not_applicable_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_applicable_tasks', to='projects.userprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='not_applicable_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
