# Generated by Django 6.0.6 on 2026-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0089_task_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
