# Generated by Django 6.0.6 on 2026-09-22 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_task_location_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('po', 'Purchase order'), ('pi', 'Proforma invoice'), ('invoice', 'Invoice'), ('other', 'Other')], max_length=10)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, default='', max_length=32)),
                ('item_description', models.TextField()),
                ('item_unit', models.CharField(blank=True, default='', max_length=20)),
                ('item_category', models.CharField(blank=True, default='', max_length=64)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='VendorOrderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_requests', to='projects.userprofile'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='decision_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_payment_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Awaiting approval'), ('approved', 'Approved — awaiting payment'), ('on_hold', 'On hold'), ('rejected', 'Rejected'), ('confirmed', 'Paid')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='statustransition',
            name='subject_type',
            field=models.CharField(choices=[('project', 'Project'), ('task', 'Task'), ('boq', 'BOQ'), ('delivery_challan', 'Delivery Challan'), ('issue', 'Issue'), ('payment_milestone', 'Payment Milestone'), ('design_assignment', 'Design Assignment'), ('payment_request', 'Payment Request')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('Residential', 'Residential'), ('OPEX', 'RESCO'), ('CAPEX', 'CAPEX')], max_length=20)),
                ('po_number', models.CharField(blank=True, default='', max_length=100)),
                ('pi_number', models.CharField(blank=True, default='', max_length=100)),
                ('raised_with_unfrozen_quantities', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vendor_orders', to='projects.userprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='projects.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='vendor_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='projects.vendororder'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['rejected', 'on_hold']), _negated=True), models.Q(('decision_reason', ''), _negated=True), _connector='OR'), name='payment_request_refusal_needs_reason'),
        ),
        migrations.AddField(
            model_name='vendororderdocument',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='projects.vendororder'),
        ),
        migrations.AddField(
            model_name='vendororderdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_order_documents', to='projects.userprofile'),
        ),
        migrations.AddField(
            model_name='vendororderline',
            name='boq_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_order_lines', to='projects.boqitem'),
        ),
        migrations.AddField(
            model_name='vendororderline',
            name='item_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_order_lines', to='projects.boqitemmaster'),
        ),
        migrations.AddField(
            model_name='vendororderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='projects.vendororder'),
        ),
        migrations.AddField(
            model_name='vendorordersite',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='projects.vendororder'),
        ),
        migrations.AddField(
            model_name='vendorordersite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_order_sites', to='projects.project'),
        ),
        migrations.AddField(
            model_name='vendorordersite',
            name='via_site_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_order_sites', to='projects.sitegroup'),
        ),
        migrations.AddConstraint(
            model_name='vendororderdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('doc_type', 'invoice'), _negated=True), models.Q(models.Q(('invoice_number', ''), _negated=True), ('invoice_amount__isnull', False), ('invoice_amount__gt', 0)), _connector='OR'), name='vendor_order_invoice_needs_number_and_amount'),
        ),
        migrations.AddConstraint(
            model_name='vendororderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='vendor_order_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='vendororderline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='vendor_order_line_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='vendorordersite',
            constraint=models.UniqueConstraint(fields=('order', 'project'), name='uniq_vendor_order_site'),
        ),
    ]
