# Generated by Django 6.0.6 on 2026-09-22 17:34

"""O2c — one invoice number per order (VendorOrderDocument, doc_type='invoice').

A plain AddConstraint. It fails, and changes nothing, if an order already carries the same
invoice number twice; no row is rewritten or deleted to make it fit. Local had 0 invoice
documents when this was written.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_payment_request_vendor_order_not_null'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendororderdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_type', 'invoice')), fields=('order', 'invoice_number'), name='uniq_invoice_number_per_order'),
        ),
    ]
