# Generated by Django 6.0.6 on 2026-09-26 16:14
"""Approvals S1 — the shared approval primitive.

Four new tables (ApprovalRequest, ApprovalStep, ApprovalAttachment,
MaterialApprovalDetail), their M2M scope tables, and the CHECK / partial UNIQUE
constraints that make a step row an accountability record. All CREATE: no existing row is
read, written or backfilled, so there is nothing to reverse beyond dropping them.

The one ALTER is StatusTransition.subject_type gaining 'approval_request' as a choice.
Choices only, exactly as 0079 was: there is no database CHECK mirroring the list, so on
PostgreSQL it is a no-op at the SQL level.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_change_request_scm_routing_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustransition',
            name='subject_type',
            field=models.CharField(choices=[('project', 'Project'), ('task', 'Task'), ('boq', 'BOQ'), ('delivery_challan', 'Delivery Challan'), ('issue', 'Issue'), ('payment_milestone', 'Payment Milestone'), ('design_assignment', 'Design Assignment'), ('payment_request', 'Payment Request'), ('approval_request', 'Approval Request')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('material_pre_order', 'Material — before order'), ('material_pre_dispatch', 'Material — before dispatch'), ('contractor_bill', 'Contractor bill')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='open', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('design_signoff_required', models.BooleanField(default=False)),
                ('current_round', models.PositiveSmallIntegerField(default=1)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_note', models.TextField(blank=True, default='')),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('programs', models.ManyToManyField(blank=True, related_name='approval_requests', to='projects.program')),
                ('projects', models.ManyToManyField(blank=True, related_name='approval_requests', to='projects.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_approval_requests', to='projects.userprofile')),
                ('site_groups', models.ManyToManyField(blank=True, related_name='approval_requests', to='projects.sitegroup')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='projects.vendor')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('file_name', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_attachments', to='projects.userprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='projects.approvalrequest')),
            ],
            options={
                'ordering': ['round', 'uploaded_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('party', models.CharField(choices=[('pm', 'PM'), ('design', 'Design Head'), ('site_engineer', 'Site Engineer')], max_length=20)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('is_proxy', models.BooleanField(default=False)),
                ('proxy_channel', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('email', 'Email'), ('in_person', 'In person')], default='', max_length=20)),
                ('proxy_evidence', models.TextField(blank=True, default='')),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_approval_steps', to='projects.userprofile')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_approval_steps', to='projects.userprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_approval_steps', to='projects.userprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='projects.approvalrequest')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_approval_steps', to='projects.userprofile')),
            ],
            options={
                'ordering': ['request', 'round', 'sequence', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MaterialApprovalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_make', models.CharField(blank=True, default='', max_length=200)),
                ('specification', models.TextField(blank=True, default='')),
                ('quantity_note', models.TextField(blank=True, default='')),
                ('boq_items', models.ManyToManyField(blank=True, related_name='material_approvals', to='projects.boqitemmaster')),
                ('pre_order_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_dispatch_details', to='projects.approvalrequest')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='material_detail', to='projects.approvalrequest')),
                ('vendor_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_approvals', to='projects.vendororder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'withdrawn'), _negated=True), models.Q(('withdrawal_note', ''), _negated=True), _connector='OR'), name='approval_request_withdrawal_note_required'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'contractor_bill'), _negated=True), ('design_signoff_required', False), _connector='OR'), name='approval_request_no_design_signoff_on_bill'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['material_pre_dispatch', 'contractor_bill']), _negated=True), ('vendor__isnull', False), _connector='OR'), name='approval_request_vendor_required_for_kind'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['approved', 'rejected', 'withdrawn']), ('closed_at__isnull', False)), models.Q(models.Q(('status__in', ['approved', 'rejected', 'withdrawn']), _negated=True), ('closed_at__isnull', True)), _connector='OR'), name='approval_request_closed_at_iff_terminal'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verdict__in', ['changes_requested', 'rejected']), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), name='approval_step_note_required'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verdict__in', ['approved', 'changes_requested', 'rejected']), ('decided_by__isnull', False), ('decided_at__isnull', False), ('recorded_by__isnull', False)), models.Q(('verdict__in', ['pending', 'superseded']), ('decided_by__isnull', True), ('decided_at__isnull', True), ('recorded_by__isnull', True)), _connector='OR'), name='approval_step_decision_fields'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verdict', 'superseded'), ('superseded_at__isnull', False)), models.Q(models.Q(('verdict', 'superseded'), _negated=True), ('superseded_at__isnull', True)), _connector='OR'), name='approval_step_superseded_at_iff_superseded'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(('is_proxy', False), models.Q(models.Q(('proxy_channel', ''), _negated=True), models.Q(('proxy_evidence', ''), _negated=True)), _connector='OR'), name='approval_step_proxy_evidence'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(('is_proxy', True), ('recorded_by', models.F('decided_by')), _connector='OR'), name='approval_step_self_recorded_unless_proxy'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(condition=models.Q(('verdict', 'superseded'), _negated=True), fields=('request', 'round', 'party'), name='uniq_approval_step_live_party'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verdict', 'superseded'), ('superseded_by__isnull', False)), models.Q(models.Q(('verdict', 'superseded'), _negated=True), ('superseded_by__isnull', True)), _connector='OR'), name='approval_step_superseded_by_iff_superseded'),
        ),
    ]
