# Generated by Django 6.0.6 on 2026-09-27 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0103_approval_primitive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoundSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['request', 'round'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='approvalstep',
            name='approval_step_self_recorded_unless_proxy',
        ),
        migrations.AddField(
            model_name='approvalattachment',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_files', to='projects.approvalstep'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='carried_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carried_into', to='projects.approvalstep'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='carry_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(('is_proxy', True), ('carried_from__isnull', False), ('recorded_by', models.F('decided_by')), _connector='OR'), name='approval_step_self_recorded_unless_proxy'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('carried_from__isnull', True), ('carry_reason', '')), models.Q(('carried_from__isnull', False), models.Q(('carry_reason', ''), _negated=True)), _connector='OR'), name='approval_step_carry_reason_iff_carried'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(('carried_from__isnull', True), ('verdict', 'approved'), _connector='OR'), name='approval_step_carried_is_approved'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(('carried_from__isnull', True), ('is_proxy', False), _connector='OR'), name='approval_step_carried_not_proxy'),
        ),
        migrations.AddField(
            model_name='approvalroundsnapshot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_round_snapshots', to='projects.userprofile'),
        ),
        migrations.AddField(
            model_name='approvalroundsnapshot',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_snapshots', to='projects.approvalrequest'),
        ),
        migrations.AddConstraint(
            model_name='approvalroundsnapshot',
            constraint=models.UniqueConstraint(fields=('request', 'round'), name='uniq_approval_round_snapshot'),
        ),
    ]
