# Generated by Django 6.0.6 on 2026-09-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0104_approval_resubmit_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalOrderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_note', models.TextField(blank=True, default='')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_links', to='projects.approvalrequest')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_order_links_made', to='projects.userprofile')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_order_links_removed', to='projects.userprofile')),
                ('vendor_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_links', to='projects.vendororder')),
            ],
            options={
                'ordering': ['approval', 'linked_at', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('approval', 'vendor_order'), name='uniq_approval_order_link_active'), models.CheckConstraint(condition=models.Q(models.Q(('removed_by__isnull', True), ('removed_at__isnull', True), ('removal_note', '')), models.Q(('removed_by__isnull', False), ('removed_at__isnull', False), models.Q(('removal_note', ''), _negated=True)), _connector='OR'), name='approval_order_link_removal_fields')],
            },
        ),
    ]
