# Generated by Django 6.0.6 on 2026-09-28 13:56
#
# Material lines on approvals (D-A28, D-A29, D-A30, D-A43).
#
# ORDER, deliberately: create the line model, check boq_items is empty, then drop it. The
# autodetector wrote the drop first; it was moved last so the retiring field is the final
# step and nothing before it depends on its absence.
#
# The emptiness check is a refusal, not a copy. A BOQ-item pick names a catalogue row, not
# a quantity or a unit, so there is nothing to turn into a line; if a pick exists, someone
# must decide what it meant before it is dropped. At build time (28 Sep 2026) the table had
# 0 rows in solarpms_local and does not exist on Railway (0103 is not deployed there yet).

import django.db.models.deletion
import django.db.models.functions.math
from django.db import migrations, models


def refuse_if_boq_items_were_picked(apps, schema_editor):
    """Stop the migration if any approval ever picked a BOQ item — dropping the column
    would lose that pick without a trace."""
    detail = apps.get_model('projects', 'MaterialApprovalDetail')
    picked = detail.boq_items.through.objects.count()
    if picked:
        raise RuntimeError(
            f'0106 refuses to drop MaterialApprovalDetail.boq_items: {picked} BOQ-item '
            f'pick(s) exist. Record them as material lines by hand (or decide they can go), '
            f'empty projects_materialapprovaldetail_boq_items, then migrate again.')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0105_approval_order_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialApprovalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=300)),
                ('make', models.CharField(blank=True, default='', max_length=200)),
                ('specification', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('Nos', 'Nos'), ('Meter', 'Meter'), ('Set', 'Set'), ('Pkt', 'Packet'), ('Pair', 'Pair'), ('Lot', 'Lot'), ('KWp', 'KWp'), ('Kg', 'Kg'), ('LS', 'Lump sum')], max_length=20)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='projects.materialapprovaldetail')),
            ],
            options={
                'ordering': ['detail', 'position'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='material_line_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit__in', ('Nos', 'Meter', 'Set', 'Pkt', 'Pair', 'Lot', 'KWp', 'Kg', 'LS'))), name='material_line_unit_known'), models.CheckConstraint(condition=models.Q(('unit__in', ('Meter', 'KWp', 'Kg', 'LS')), ('quantity', django.db.models.functions.math.Floor(models.F('quantity'))), _connector='OR'), name='material_line_count_unit_whole'), models.UniqueConstraint(fields=('detail', 'position'), name='uniq_material_line_position')],
            },
        ),
        migrations.RunPython(refuse_if_boq_items_were_picked, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='materialapprovaldetail',
            name='boq_items',
        ),
    ]
