# Generated by Django 6.0.6 on 2026-09-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0106_material_approval_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Test or demo data. Hidden from the CEO dashboard.'),
        ),
    ]
