# Generated by Django 6.0.6 on 2026-09-29 10:47
#
# Contractor bills 4a-1. Safe on production data with no manual step: every existing
# vendor takes the column default, 'supplier' (D-A14), which vendor_kind_known accepts;
# the two new tables start empty. No existing approval row is touched — no contractor
# bill can have been raised before this (the raise page refuses the kind).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0107_project_is_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_number', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('pdf_file_name', models.CharField(max_length=255)),
                ('pdf_bucket', models.CharField(max_length=100)),
                ('pdf_path', models.CharField(max_length=500)),
                ('pdf_size_kb', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContractorBillTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['detail', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='kind',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('contractor', 'Contractor'), ('both', 'Supplier and contractor')], default='supplier', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['supplier', 'contractor', 'both'])), name='vendor_kind_known'),
        ),
        migrations.AddField(
            model_name='contractorbilldetail',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_bills', to='projects.project'),
        ),
        migrations.AddField(
            model_name='contractorbilldetail',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill_detail', to='projects.approvalrequest'),
        ),
        migrations.AddField(
            model_name='contractorbilltask',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_links', to='projects.contractorbilldetail'),
        ),
        migrations.AddField(
            model_name='contractorbilltask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_links', to='projects.task'),
        ),
        migrations.AddField(
            model_name='contractorbilldetail',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='contractor_bills', through='projects.ContractorBillTask', to='projects.task'),
        ),
        migrations.AddConstraint(
            model_name='contractorbilltask',
            constraint=models.UniqueConstraint(fields=('detail', 'task'), name='uniq_contractor_bill_task'),
        ),
        migrations.AddConstraint(
            model_name='contractorbilldetail',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='contractor_bill_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='contractorbilldetail',
            constraint=models.CheckConstraint(condition=models.Q(('bill_number', ''), _negated=True), name='contractor_bill_number_required'),
        ),
        migrations.AddConstraint(
            model_name='contractorbilldetail',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pdf_file_name', ''), _negated=True), models.Q(('pdf_bucket', ''), _negated=True), models.Q(('pdf_path', ''), _negated=True)), name='contractor_bill_pdf_required'),
        ),
    ]
