# Generated by Django 6.0.6 on 2026-09-30 04:47
#
# Payments 5a (D-A56): a payment may belong to a contractor bill instead of a PO/PI
# record. No data step: the new column starts NULL and vendor_order only loses NOT NULL,
# so every existing row (an order, no bill) satisfies payment_request_order_xor_bill as
# it is added. Rehearsed on a copy of solarpms_local migrated to 0108 first.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0108_contractor_bills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='contractor_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='projects.contractorbilldetail'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='vendor_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='projects.vendororder'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('vendor_order__isnull', False), ('contractor_bill__isnull', True)), models.Q(('vendor_order__isnull', True), ('contractor_bill__isnull', False)), _connector='OR'), name='payment_request_order_xor_bill'),
        ),
    ]
