# Generated by Django 6.0.6 on 2026-10-08 05:38
#
# Closeout step 2 (CL-1): a punch point can be Closed by its task's approval. Adds
# the three closure columns, the Closed status value, and the CHECK that ties them
# together. No data step here: every existing row is Open or Waived with NULL/blank
# closure columns, so it satisfies punchpoint_closure_columns_match_status as the
# constraint is added. The one-off retroactive closure is 0111.
#
# REVERSE REOPENS CLOSED POINTS. Unapplying this migration drops the closure columns
# but would leave status='Closed' behind; re-applying it would then add NULL
# closure columns beside 'Closed' and the CHECK would refuse the whole migration.
# So the last operation, reversed first while the columns still exist, puts every
# Closed point back to Open with its closure columns cleared - the state the code
# before this migration (which has no Closed) would have left it in.

import django.db.models.deletion
from django.db import migrations, models


def reopen_closed_points(apps, schema_editor):
    """Reverse only: Closed -> Open, closure columns cleared (see header)."""
    PunchPoint = apps.get_model('projects', 'PunchPoint')
    # Race: none in practice. A rollback is run with the app stopped, inside the
    # migration's own transaction, so no approval can close a point mid-update.
    PunchPoint.objects.filter(status='Closed').update(
        status='Open', closed_by=None, closed_at=None, closure_method='')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0109_payment_contractor_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchpoint',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punchpoint',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_punch_points', to='projects.userprofile'),
        ),
        migrations.AddField(
            model_name='punchpoint',
            name='closure_method',
            field=models.CharField(blank=True, choices=[('approval', 'Closed on approval'), ('self_certified', 'Closed on self-certified approval'), ('retroactive', 'Closed retroactively (CL-1)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='punchpoint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Waived', 'Waived'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='punchpoint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status', 'Closed'), models.Q(('closure_method', ''), _negated=True)), models.Q(models.Q(('status', 'Closed'), _negated=True), ('closed_at__isnull', True), ('closed_by__isnull', True), ('closure_method', '')), _connector='OR'), name='punchpoint_closure_columns_match_status'),
        ),
        migrations.RunPython(migrations.RunPython.noop, reopen_closed_points),
    ]
