# Generated by Django 6.0.6 on 2026-10-08 06:43
#
# Closeout step 3 (CL-9): SiteQaqcAssignment, the dated naming of one OPEX site's
# QA/QC engineer. Schema only: a new table, no rows written and no existing table
# touched, so it is safe on a live database and reverses by dropping the table.
# Nothing is backfilled - production has no QA/QC engineer to carry over (Q-0: no
# is_qaqc holders), and PMs assign them through the new screen.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0111_close_stale_punch_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteQaqcAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('replaced', 'Replaced by another engineer'), ('ended', 'Ended')], default='', max_length=10)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_assignments_made', to='projects.userprofile')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_assignments_ended', to='projects.userprofile')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_site_assignments', to='projects.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_assignments', to='projects.project')),
            ],
            options={
                'ordering': ['project', '-assigned_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('project',), name='uniq_site_qaqc_active'), models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('ended_by__isnull', True), ('end_reason', '')), models.Q(('ended_at__isnull', False), ('ended_by__isnull', False), models.Q(('end_reason', ''), _negated=True)), _connector='OR'), name='site_qaqc_end_fields'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('assigned_at')), _connector='OR'), name='site_qaqc_ends_after_start')],
            },
        ),
    ]
