# Generated by Django 6.0.6 on 2026-10-08 10:30
#
# Closeout step 4 (CL-3): CodRecord, an OPEX site's recorded COD with its evidence PDF.
# Schema only: a new table, no rows written and no existing table touched, so it is
# safe on a live database and reverses by dropping the table. Nothing is backfilled -
# no COD has been recorded anywhere (every COD mirror reads Not Started), and the
# mirror is moved only by cod_views' writers, never by this migration.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0112_site_qaqc_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_date', models.DateField()),
                ('evidence_type', models.CharField(choices=[('discom_letter', 'DISCOM letter'), ('net_meter_installation', 'Net-meter installation'), ('commissioning_report', 'Commissioning report')], max_length=30)),
                ('pdf_file_name', models.CharField(max_length=255)),
                ('pdf_bucket', models.CharField(max_length=100)),
                ('pdf_path', models.CharField(max_length=500)),
                ('pdf_size_kb', models.PositiveIntegerField(default=0)),
                ('note', models.TextField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdraw_reason', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cod_records', to='projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cod_records_made', to='projects.userprofile')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cod_records_withdrawn', to='projects.userprofile')),
            ],
            options={
                'ordering': ['project', '-recorded_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('withdrawn_at__isnull', True)), fields=('project',), name='uniq_cod_record_active'), models.CheckConstraint(condition=models.Q(models.Q(('withdrawn_at__isnull', True), ('withdrawn_by__isnull', True), ('withdraw_reason', '')), models.Q(('withdrawn_at__isnull', False), ('withdrawn_by__isnull', False), models.Q(('withdraw_reason', ''), _negated=True)), _connector='OR'), name='cod_record_withdraw_fields'), models.CheckConstraint(condition=models.Q(('withdrawn_at__isnull', True), ('withdrawn_at__gte', models.F('recorded_at')), _connector='OR'), name='cod_record_withdrawn_after_recorded'), models.CheckConstraint(condition=models.Q(('note', ''), _negated=True), name='cod_record_note_required'), models.CheckConstraint(condition=models.Q(('evidence_type__in', ['discom_letter', 'net_meter_installation', 'commissioning_report'])), name='cod_record_evidence_type_valid'), models.CheckConstraint(condition=models.Q(models.Q(('pdf_file_name', ''), _negated=True), models.Q(('pdf_bucket', ''), _negated=True), models.Q(('pdf_path', ''), _negated=True)), name='cod_record_pdf_required')],
            },
        ),
    ]
